"""shell_data_reporting_ap_is.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""


class PricedTransactionReqV2PeriodEnum(object):
    """Implementation of the 'PricedTransactionReqV2Period' enum.

    Pass below one of the value as per the required transaction period
    1. Last 7 Days
    2. Last 30 Days
    3. Last 90 Days

    Attributes:
        ENUM_1: The enum member of type int.
        ENUM_2: The enum member of type int.
        ENUM_3: The enum member of type int.

    """

    ENUM_1 = 1

    ENUM_2 = 2

    ENUM_3 = 3

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
