# -*- coding: utf-8 -*-

"""
jwttester

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os
import unittest
from tests.http_response_catcher import HttpResponseCatcher
from jwttester.configuration import Configuration, Environment
from jwttester.jwttester_client import JwttesterClient
from jwttester.http.auth.o_auth_2 import BearerAuthCredentials


class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    client = None
    config = None

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 100
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = JwttesterClient(config=cls.config)

    @staticmethod
    def create_configuration():
        return Configuration.from_environment(
            bearer_auth_credentials=BearerAuthCredentials(
                access_token='0b79bab50daca910b000d4f1a2b675d604257e42'),
            environment=Environment.TESTING,
            http_call_back=HttpResponseCatcher())
