"""typecombinatorglobal.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from typecombinatorglobal.api_helper import (
    APIHelper,
)


class Animal(object):
    """Implementation of the 'Animal' model.

    Attributes:
        pet_type (str): The model property of type str.
        id (str | int | None): AnyOf with primitive types and metadata.
        friend (Lion | Deer | None): allOf (LionVsDeer) and its an alias of
            LionVsDeer
        enemy (Lion | Squirrel | None): OneOf (Lion, Squirrel) with an
            additional "kind" property discriminator of mapping
            (northener:Lion, westener:Squirrel)
        kind (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "pet_type": "pet_type",
        "id": "id",
        "friend": "friend",
        "enemy": "enemy",
        "kind": "kind",
    }

    _optionals = [
        "pet_type",
        "id",
        "friend",
        "enemy",
        "kind",
    ]

    def __init__(self,
                 pet_type="Animal",
                 id=APIHelper.SKIP,
                 friend=APIHelper.SKIP,
                 enemy=APIHelper.SKIP,
                 kind=APIHelper.SKIP):
        """Initialize a Animal instance."""
        # Initialize members of the class
        self.pet_type = pet_type
        if id is not APIHelper.SKIP:
            self.id = id
        if friend is not APIHelper.SKIP:
            self.friend = friend
        if enemy is not APIHelper.SKIP:
            self.enemy = enemy
        if kind is not APIHelper.SKIP:
            self.kind = kind

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from typecombinatorglobal.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        discriminators = {
            "Cat": Cat.from_dictionary,
            "Dog": Dog.from_dictionary,
        }
        unboxer = discriminators.get(dictionary.get("pet_type"))

        # Delegate unboxing to another function if a discriminator
        # value for a child class is present.
        if unboxer:
            return unboxer(dictionary)

        # Extract variables from the dictionary
        pet_type =\
            dictionary.get("pet_type")\
            if dictionary.get("pet_type") else "Animal"
        id = APIHelper.deserialize_union_type(UnionTypeLookUp.get("AnyOfPrimitive2"), dictionary.get("id"), False) if dictionary.get("id") is not None else APIHelper.SKIP
        friend = APIHelper.deserialize_union_type(UnionTypeLookUp.get("OneOfLionDeerType3"), dictionary.get("friend"), False) if dictionary.get("friend") is not None else APIHelper.SKIP
        enemy = APIHelper.deserialize_union_type(UnionTypeLookUp.get("OneOfLionSquirrelAreaKind2"), dictionary.get("enemy"), False) if dictionary.get("enemy") is not None else APIHelper.SKIP
        kind =\
            dictionary.get("kind")\
            if dictionary.get("kind") else APIHelper.SKIP
        # Return an object of this model
        return cls(pet_type,
                   id,
                   friend,
                   enemy,
                   kind)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        discriminators = {
            "Cat": Cat.validate,
            "Dog": Dog.validate,
        }

        validator  = discriminators.get(dictionary.get("pet_type"))

        # Delegate validation to another function if a discriminator
        # value for a child class is present.
        if validator :
            return validator(dictionary)

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"pet_type={(self.pet_type
                     if hasattr(self, 'pet_type') else None)!r}, "
                f"id={(self.id if hasattr(self, 'id') else None)!r}, "
                f"friend={(self.friend if hasattr(self, 'friend') else None)!r}, "
                f"enemy={(self.enemy if hasattr(self, 'enemy') else None)!r}, "
                f"kind={(self.kind if hasattr(self, 'kind') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"pet_type={(self.pet_type
                     if hasattr(self, 'pet_type') else None)!s}, "
                f"id={(self.id if hasattr(self, 'id') else None)!s}, "
                f"friend={(self.friend if hasattr(self, 'friend') else None)!s}, "
                f"enemy={(self.enemy if hasattr(self, 'enemy') else None)!s}, "
                f"kind={(self.kind if hasattr(self, 'kind') else None)!s})")

class Cat(Animal):
    """Implementation of the 'Cat' model.
    NOTE: This class inherits from 'Animal'.

    Attributes:
        name (str): The model property of type str.
        color (str): The model property of type str.
        one_of_kind (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "color": "color",
        "one_of_kind": "One Of kind",
        "pet_type": "pet_type",
        "id": "id",
        "friend": "friend",
        "enemy": "enemy",
        "kind": "kind",
    }

    _optionals = [
        "one_of_kind",
    ]
    _optionals.extend(Animal._optionals)

    def __init__(self,
                 name=None,
                 color=None,
                 one_of_kind=APIHelper.SKIP,
                 pet_type="Cat",
                 id=APIHelper.SKIP,
                 friend=APIHelper.SKIP,
                 enemy=APIHelper.SKIP,
                 kind=APIHelper.SKIP):
        """Initialize a Cat instance."""
        # Initialize members of the class
        self.name = name
        self.color = color
        if one_of_kind is not APIHelper.SKIP:
            self.one_of_kind = one_of_kind

        # Call the constructor for the base class
        super(Cat, self).__init__(pet_type,
                                  id,
                                  friend,
                                  enemy,
                                  kind)

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from typecombinatorglobal.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get("name") if dictionary.get("name") else None
        color = dictionary.get("color") if dictionary.get("color") else None
        one_of_kind =\
            dictionary.get("One Of kind")\
            if dictionary.get("One Of kind") else APIHelper.SKIP
        pet_type =\
            dictionary.get("pet_type")\
            if dictionary.get("pet_type") else "Cat"
        id = APIHelper.deserialize_union_type(UnionTypeLookUp.get("AnyOfPrimitive2"), dictionary.get("id"), False) if dictionary.get("id") is not None else APIHelper.SKIP
        friend = APIHelper.deserialize_union_type(UnionTypeLookUp.get("OneOfLionDeerType3"), dictionary.get("friend"), False) if dictionary.get("friend") is not None else APIHelper.SKIP
        enemy = APIHelper.deserialize_union_type(UnionTypeLookUp.get("OneOfLionSquirrelAreaKind2"), dictionary.get("enemy"), False) if dictionary.get("enemy") is not None else APIHelper.SKIP
        kind =\
            dictionary.get("kind")\
            if dictionary.get("kind") else APIHelper.SKIP
        # Return an object of this model
        return cls(name,
                   color,
                   one_of_kind,
                   pet_type,
                   id,
                   friend,
                   enemy,
                   kind)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                value=dictionary.name,
                type_callable=lambda value: isinstance(value, str)) \
                and APIHelper.is_valid_type(
                value=dictionary.color,
                type_callable=lambda value: isinstance(value, str))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
            value=dictionary.get("name"),
            type_callable=lambda value: isinstance(value, str)) \
            and APIHelper.is_valid_type(
            value=dictionary.get("color"),
            type_callable=lambda value: isinstance(value, str))

    def __repr__(self):
        """Return a unambiguous string representation."""
        base_repr = super().__repr__()
        return (f"{self.__class__.__name__}("
                f"{base_repr[base_repr.find('(') + 1:-1]}, "
                f"name={self.name!r}, "
                f"color={self.color!r}, "
                f"one_of_kind={(self.one_of_kind
                     if hasattr(self, 'one_of_kind') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        base_str = super().__str__()
        return (f"{self.__class__.__name__}("
                f"{base_str[base_str.find('(') + 1:-1]}, "
                f"name={self.name!s}, "
                f"color={self.color!s}, "
                f"one_of_kind={(self.one_of_kind
                     if hasattr(self, 'one_of_kind') else None)!s})")

class Dog(Animal):
    """Implementation of the 'Dog' model.
    NOTE: This class inherits from 'Animal'.

    Attributes:
        name (str): The model property of type str.
        fangs (str): The model property of type str.
        one_of_kind (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "name": "name",
        "fangs": "fangs",
        "one_of_kind": "One Of kind",
        "pet_type": "pet_type",
        "id": "id",
        "friend": "friend",
        "enemy": "enemy",
        "kind": "kind",
    }

    _optionals = [
        "one_of_kind",
    ]
    _optionals.extend(Animal._optionals)

    def __init__(self,
                 name=None,
                 fangs=None,
                 one_of_kind=APIHelper.SKIP,
                 pet_type="Dog",
                 id=APIHelper.SKIP,
                 friend=APIHelper.SKIP,
                 enemy=APIHelper.SKIP,
                 kind=APIHelper.SKIP):
        """Initialize a Dog instance."""
        # Initialize members of the class
        self.name = name
        self.fangs = fangs
        if one_of_kind is not APIHelper.SKIP:
            self.one_of_kind = one_of_kind

        # Call the constructor for the base class
        super(Dog, self).__init__(pet_type,
                                  id,
                                  friend,
                                  enemy,
                                  kind)

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from typecombinatorglobal.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        name = dictionary.get("name") if dictionary.get("name") else None
        fangs = dictionary.get("fangs") if dictionary.get("fangs") else None
        one_of_kind =\
            dictionary.get("One Of kind")\
            if dictionary.get("One Of kind") else APIHelper.SKIP
        pet_type =\
            dictionary.get("pet_type")\
            if dictionary.get("pet_type") else "Dog"
        id = APIHelper.deserialize_union_type(UnionTypeLookUp.get("AnyOfPrimitive2"), dictionary.get("id"), False) if dictionary.get("id") is not None else APIHelper.SKIP
        friend = APIHelper.deserialize_union_type(UnionTypeLookUp.get("OneOfLionDeerType3"), dictionary.get("friend"), False) if dictionary.get("friend") is not None else APIHelper.SKIP
        enemy = APIHelper.deserialize_union_type(UnionTypeLookUp.get("OneOfLionSquirrelAreaKind2"), dictionary.get("enemy"), False) if dictionary.get("enemy") is not None else APIHelper.SKIP
        kind =\
            dictionary.get("kind")\
            if dictionary.get("kind") else APIHelper.SKIP
        # Return an object of this model
        return cls(name,
                   fangs,
                   one_of_kind,
                   pet_type,
                   id,
                   friend,
                   enemy,
                   kind)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(
                value=dictionary.name,
                type_callable=lambda value: isinstance(value, str)) \
                and APIHelper.is_valid_type(
                value=dictionary.fangs,
                type_callable=lambda value: isinstance(value, str))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(
            value=dictionary.get("name"),
            type_callable=lambda value: isinstance(value, str)) \
            and APIHelper.is_valid_type(
            value=dictionary.get("fangs"),
            type_callable=lambda value: isinstance(value, str))

    def __repr__(self):
        """Return a unambiguous string representation."""
        base_repr = super().__repr__()
        return (f"{self.__class__.__name__}("
                f"{base_repr[base_repr.find('(') + 1:-1]}, "
                f"name={self.name!r}, "
                f"fangs={self.fangs!r}, "
                f"one_of_kind={(self.one_of_kind
                     if hasattr(self, 'one_of_kind') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        base_str = super().__str__()
        return (f"{self.__class__.__name__}("
                f"{base_str[base_str.find('(') + 1:-1]}, "
                f"name={self.name!s}, "
                f"fangs={self.fangs!s}, "
                f"one_of_kind={(self.one_of_kind
                     if hasattr(self, 'one_of_kind') else None)!s})")
