# -*- coding: utf-8 -*-

"""
foxitesigntest

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from foxitesigntest.api_helper import APIHelper
from foxitesigntest.models.custom_field import CustomField
from foxitesigntest.models.party import Party


class DraftEnvelope(object):

    """Implementation of the 'DraftEnvelope' model.

    An Envelope meant to be used when sending documents via URLs

    Attributes:
        folder_id (int): Envelope Id that has been saved in the draft with
            documents.
        folder_name (str): Name of the document(s) folder
        parties (List[Party]): List of recipient parties can be added in the
            draft. Every entry must contain firstName, lastName, emailId,
            permission and sequence fields.
        sign_in_sequence (bool): This field is used to determine whether
            recipients will sign the envelope documents in a sequence. If
            false, then all the recipients receive invitation email
            simultaneously. When true, then each recipient receives invitation
            email successively after previous recipient completes the required
            task, like signing the documents or filling fields, etc.
        in_person_enable (bool): This field is used to initiate the in-person
            signing process which can be easily completed on any device in a
            matter of minutes and avoids email based signatures where
            required. If false, then all the recipients receive the invitation
            email simultaneously. When true, then in-person administrator
            receives an invitation email to initiate the signing process for
            the signer.
        fields (List[Any]): The model property of type List[Any].
        send_now (bool): Use this field to send the folder to the recipient
            parties. Each party will then receive a unique link in their email
            to sign the document. The invitation mail and subject in this case
            will be the same as the default invitation mail setup in your
            account.
        create_embedded_signing_session (bool): Signing session token will be
            generated without sending out emails to the recipients.
        embedded_signers_email_ids (List[str]): An array of email ids of
            recipients for whom an embedded signing session needs to be
            created. The email ids from the recipient parties added in the
            parties list.
        custom_field_1 (CustomField): Maximum of two custom fields can be
            passed to Foxit eSign via API that are stored at the folder level.
            Webhook response includes these custom field.
        sign_success_url (str): Enter the absolute URL for the signers who
            will be redirected to after successfully signing in embedded
            signing view.
        sign_decline_url (str): Enter the absolute URL for the signers who
            will be redirected to if declines to sign in embedded signing view.
        sign_later_url (str): Enter the absolute URL for the signers who will
            be redirected to if chooses to sign later in embedded signing view.
        sign_error_url (str): Enter the absolute URL for the signers who will
            be redirected to if error comes during signing the document in
            embedded signing view.
        allow_send_now_and_embedded_signing_session (bool): If set as true,
            Foxit eSign will send unique signing link to each recipient. This
            is ONLY applicable when parameters sendNow and
            createEmbeddedSigningSession is true.
        allow_advanced_email_validation (bool): Validate the email address of
            the parties when set as true.
        sign_success_url_all_parties (bool): If set as true, signer will be
            redirected to URL provided in the signSuccessUrl after
            successfully signing. This is only applicable when the sendNow is
            true.
        email_template_id (int): Pass the email template Id to send the email
            templates other than default email templates.
        signer_instruction_id (int): Pass the instruction Id to send signer
            instructions other than the default signer instructions
        confirmation_instruction_id (int): Pass the confirmation instruction
            id to send confirmation instructions other than the default
            confirmation instructions.
        theme_color (str): Enter the CSS value to set the theme color.
        session_expire (bool): Set as true to initiate the expire of the
            embedded signing session.
        expiry (int): Required if sessionExpire is true. Enter duration in
            milliseconds of the expiry on the embedded signing session.
        sender_email (str): enter email of another user in your account which
            will be used for sending this document(s) folder to the recipient
            parties.
        create_executed_folder (bool): If true, Envelope automatically
            executed with existing party.
        hide_field_name_for_recipients (bool): Hide field names for Recipients
            for Data Entry Fields and Advanced Fields. (Except Radio button,
            Checkbox, Image and Hyperlink).
        hide_checkbox_border (bool): Borders of Checkbox will be hidden in the
            executed documents.
        hide_decline_to_sign (bool): If true, it will hide the option of
            "Decline to Sign" for the signer.
        hide_more_action (bool): If true, it will hide "More Actions" button
            in sending/signing session. In case of "Send Now": true, it will
            not hide anything.
        hide_next_required_fieldbtn (bool): The model property of type bool.
        folder_password (str): This password will be required by the
            signer/author in order to open the digitally signed document. If
            the parameter is kept blank then no password will be required to
            open the digitally signed document.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "folder_id": 'folderId',
        "folder_name": 'folderName',
        "parties": 'parties',
        "sign_in_sequence": 'signInSequence',
        "in_person_enable": 'inPersonEnable',
        "fields": 'fields',
        "send_now": 'sendNow',
        "create_embedded_signing_session": 'createEmbeddedSigningSession',
        "embedded_signers_email_ids": 'embeddedSignersEmailIds',
        "custom_field_1": 'custom_field1',
        "sign_success_url": 'signSuccessUrl',
        "sign_decline_url": 'signDeclineUrl',
        "sign_later_url": 'signLaterUrl',
        "sign_error_url": 'signErrorUrl',
        "allow_send_now_and_embedded_signing_session": 'allowSendNowAndEmbeddedSigningSession',
        "allow_advanced_email_validation": 'allowAdvancedEmailValidation',
        "sign_success_url_all_parties": 'signSuccessUrlAllParties',
        "email_template_id": 'emailTemplateId',
        "signer_instruction_id": 'signerInstructionId',
        "confirmation_instruction_id": 'confirmationInstructionId',
        "theme_color": 'themeColor',
        "session_expire": 'sessionExpire',
        "expiry": 'expiry',
        "sender_email": 'senderEmail',
        "create_executed_folder": 'createExecutedFolder',
        "hide_field_name_for_recipients": 'hideFieldNameForRecipients',
        "hide_checkbox_border": 'hideCheckboxBorder',
        "hide_decline_to_sign": 'hideDeclineToSign',
        "hide_more_action": 'hideMoreAction',
        "hide_next_required_fieldbtn": 'hideNextRequiredFieldbtn',
        "folder_password": 'folderPassword'
    }

    _optionals = [
        'sign_in_sequence',
        'in_person_enable',
        'fields',
        'send_now',
        'create_embedded_signing_session',
        'embedded_signers_email_ids',
        'custom_field_1',
        'sign_success_url',
        'sign_decline_url',
        'sign_later_url',
        'sign_error_url',
        'allow_send_now_and_embedded_signing_session',
        'allow_advanced_email_validation',
        'sign_success_url_all_parties',
        'email_template_id',
        'signer_instruction_id',
        'confirmation_instruction_id',
        'theme_color',
        'session_expire',
        'expiry',
        'sender_email',
        'create_executed_folder',
        'hide_field_name_for_recipients',
        'hide_checkbox_border',
        'hide_decline_to_sign',
        'hide_more_action',
        'hide_next_required_fieldbtn',
        'folder_password',
    ]

    def __init__(self,
                 folder_id=None,
                 folder_name=None,
                 parties=None,
                 sign_in_sequence=False,
                 in_person_enable=False,
                 fields=APIHelper.SKIP,
                 send_now=True,
                 create_embedded_signing_session=False,
                 embedded_signers_email_ids=APIHelper.SKIP,
                 custom_field_1=APIHelper.SKIP,
                 sign_success_url=APIHelper.SKIP,
                 sign_decline_url=APIHelper.SKIP,
                 sign_later_url=APIHelper.SKIP,
                 sign_error_url=APIHelper.SKIP,
                 allow_send_now_and_embedded_signing_session=False,
                 allow_advanced_email_validation=False,
                 sign_success_url_all_parties=False,
                 email_template_id=APIHelper.SKIP,
                 signer_instruction_id=APIHelper.SKIP,
                 confirmation_instruction_id=APIHelper.SKIP,
                 theme_color=APIHelper.SKIP,
                 session_expire=False,
                 expiry=APIHelper.SKIP,
                 sender_email=APIHelper.SKIP,
                 create_executed_folder=False,
                 hide_field_name_for_recipients=False,
                 hide_checkbox_border=False,
                 hide_decline_to_sign=False,
                 hide_more_action=False,
                 hide_next_required_fieldbtn=False,
                 folder_password=APIHelper.SKIP):
        """Constructor for the DraftEnvelope class"""

        # Initialize members of the class
        self.folder_id = folder_id 
        self.folder_name = folder_name 
        self.parties = parties 
        self.sign_in_sequence = sign_in_sequence 
        self.in_person_enable = in_person_enable 
        if fields is not APIHelper.SKIP:
            self.fields = fields 
        self.send_now = send_now 
        self.create_embedded_signing_session = create_embedded_signing_session 
        if embedded_signers_email_ids is not APIHelper.SKIP:
            self.embedded_signers_email_ids = embedded_signers_email_ids 
        if custom_field_1 is not APIHelper.SKIP:
            self.custom_field_1 = custom_field_1 
        if sign_success_url is not APIHelper.SKIP:
            self.sign_success_url = sign_success_url 
        if sign_decline_url is not APIHelper.SKIP:
            self.sign_decline_url = sign_decline_url 
        if sign_later_url is not APIHelper.SKIP:
            self.sign_later_url = sign_later_url 
        if sign_error_url is not APIHelper.SKIP:
            self.sign_error_url = sign_error_url 
        self.allow_send_now_and_embedded_signing_session = allow_send_now_and_embedded_signing_session 
        self.allow_advanced_email_validation = allow_advanced_email_validation 
        self.sign_success_url_all_parties = sign_success_url_all_parties 
        if email_template_id is not APIHelper.SKIP:
            self.email_template_id = email_template_id 
        if signer_instruction_id is not APIHelper.SKIP:
            self.signer_instruction_id = signer_instruction_id 
        if confirmation_instruction_id is not APIHelper.SKIP:
            self.confirmation_instruction_id = confirmation_instruction_id 
        if theme_color is not APIHelper.SKIP:
            self.theme_color = theme_color 
        self.session_expire = session_expire 
        if expiry is not APIHelper.SKIP:
            self.expiry = expiry 
        if sender_email is not APIHelper.SKIP:
            self.sender_email = sender_email 
        self.create_executed_folder = create_executed_folder 
        self.hide_field_name_for_recipients = hide_field_name_for_recipients 
        self.hide_checkbox_border = hide_checkbox_border 
        self.hide_decline_to_sign = hide_decline_to_sign 
        self.hide_more_action = hide_more_action 
        self.hide_next_required_fieldbtn = hide_next_required_fieldbtn 
        if folder_password is not APIHelper.SKIP:
            self.folder_password = folder_password 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        folder_id = dictionary.get("folderId") if dictionary.get("folderId") else None
        folder_name = dictionary.get("folderName") if dictionary.get("folderName") else None
        parties = None
        if dictionary.get('parties') is not None:
            parties = [Party.from_dictionary(x) for x in dictionary.get('parties')]
        sign_in_sequence = dictionary.get("signInSequence") if dictionary.get("signInSequence") else False
        in_person_enable = dictionary.get("inPersonEnable") if dictionary.get("inPersonEnable") else False
        fields = dictionary.get("fields") if dictionary.get("fields") else APIHelper.SKIP
        send_now = dictionary.get("sendNow") if dictionary.get("sendNow") else True
        create_embedded_signing_session = dictionary.get("createEmbeddedSigningSession") if dictionary.get("createEmbeddedSigningSession") else False
        embedded_signers_email_ids = dictionary.get("embeddedSignersEmailIds") if dictionary.get("embeddedSignersEmailIds") else APIHelper.SKIP
        custom_field_1 = CustomField.from_dictionary(dictionary.get('custom_field1')) if 'custom_field1' in dictionary.keys() else APIHelper.SKIP
        sign_success_url = dictionary.get("signSuccessUrl") if dictionary.get("signSuccessUrl") else APIHelper.SKIP
        sign_decline_url = dictionary.get("signDeclineUrl") if dictionary.get("signDeclineUrl") else APIHelper.SKIP
        sign_later_url = dictionary.get("signLaterUrl") if dictionary.get("signLaterUrl") else APIHelper.SKIP
        sign_error_url = dictionary.get("signErrorUrl") if dictionary.get("signErrorUrl") else APIHelper.SKIP
        allow_send_now_and_embedded_signing_session = dictionary.get("allowSendNowAndEmbeddedSigningSession") if dictionary.get("allowSendNowAndEmbeddedSigningSession") else False
        allow_advanced_email_validation = dictionary.get("allowAdvancedEmailValidation") if dictionary.get("allowAdvancedEmailValidation") else False
        sign_success_url_all_parties = dictionary.get("signSuccessUrlAllParties") if dictionary.get("signSuccessUrlAllParties") else False
        email_template_id = dictionary.get("emailTemplateId") if dictionary.get("emailTemplateId") else APIHelper.SKIP
        signer_instruction_id = dictionary.get("signerInstructionId") if dictionary.get("signerInstructionId") else APIHelper.SKIP
        confirmation_instruction_id = dictionary.get("confirmationInstructionId") if dictionary.get("confirmationInstructionId") else APIHelper.SKIP
        theme_color = dictionary.get("themeColor") if dictionary.get("themeColor") else APIHelper.SKIP
        session_expire = dictionary.get("sessionExpire") if dictionary.get("sessionExpire") else False
        expiry = dictionary.get("expiry") if dictionary.get("expiry") else APIHelper.SKIP
        sender_email = dictionary.get("senderEmail") if dictionary.get("senderEmail") else APIHelper.SKIP
        create_executed_folder = dictionary.get("createExecutedFolder") if dictionary.get("createExecutedFolder") else False
        hide_field_name_for_recipients = dictionary.get("hideFieldNameForRecipients") if dictionary.get("hideFieldNameForRecipients") else False
        hide_checkbox_border = dictionary.get("hideCheckboxBorder") if dictionary.get("hideCheckboxBorder") else False
        hide_decline_to_sign = dictionary.get("hideDeclineToSign") if dictionary.get("hideDeclineToSign") else False
        hide_more_action = dictionary.get("hideMoreAction") if dictionary.get("hideMoreAction") else False
        hide_next_required_fieldbtn = dictionary.get("hideNextRequiredFieldbtn") if dictionary.get("hideNextRequiredFieldbtn") else False
        folder_password = dictionary.get("folderPassword") if dictionary.get("folderPassword") else APIHelper.SKIP
        # Return an object of this model
        return cls(folder_id,
                   folder_name,
                   parties,
                   sign_in_sequence,
                   in_person_enable,
                   fields,
                   send_now,
                   create_embedded_signing_session,
                   embedded_signers_email_ids,
                   custom_field_1,
                   sign_success_url,
                   sign_decline_url,
                   sign_later_url,
                   sign_error_url,
                   allow_send_now_and_embedded_signing_session,
                   allow_advanced_email_validation,
                   sign_success_url_all_parties,
                   email_template_id,
                   signer_instruction_id,
                   confirmation_instruction_id,
                   theme_color,
                   session_expire,
                   expiry,
                   sender_email,
                   create_executed_folder,
                   hide_field_name_for_recipients,
                   hide_checkbox_border,
                   hide_decline_to_sign,
                   hide_more_action,
                   hide_next_required_fieldbtn,
                   folder_password)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'folder_id={self.folder_id!r}, '
                f'folder_name={self.folder_name!r}, '
                f'parties={self.parties!r}, '
                f'sign_in_sequence={(self.sign_in_sequence if hasattr(self, "sign_in_sequence") else None)!r}, '
                f'in_person_enable={(self.in_person_enable if hasattr(self, "in_person_enable") else None)!r}, '
                f'fields={(self.fields if hasattr(self, "fields") else None)!r}, '
                f'send_now={(self.send_now if hasattr(self, "send_now") else None)!r}, '
                f'create_embedded_signing_session={(self.create_embedded_signing_session if hasattr(self, "create_embedded_signing_session") else None)!r}, '
                f'embedded_signers_email_ids={(self.embedded_signers_email_ids if hasattr(self, "embedded_signers_email_ids") else None)!r}, '
                f'custom_field_1={(self.custom_field_1 if hasattr(self, "custom_field_1") else None)!r}, '
                f'sign_success_url={(self.sign_success_url if hasattr(self, "sign_success_url") else None)!r}, '
                f'sign_decline_url={(self.sign_decline_url if hasattr(self, "sign_decline_url") else None)!r}, '
                f'sign_later_url={(self.sign_later_url if hasattr(self, "sign_later_url") else None)!r}, '
                f'sign_error_url={(self.sign_error_url if hasattr(self, "sign_error_url") else None)!r}, '
                f'allow_send_now_and_embedded_signing_session={(self.allow_send_now_and_embedded_signing_session if hasattr(self, "allow_send_now_and_embedded_signing_session") else None)!r}, '
                f'allow_advanced_email_validation={(self.allow_advanced_email_validation if hasattr(self, "allow_advanced_email_validation") else None)!r}, '
                f'sign_success_url_all_parties={(self.sign_success_url_all_parties if hasattr(self, "sign_success_url_all_parties") else None)!r}, '
                f'email_template_id={(self.email_template_id if hasattr(self, "email_template_id") else None)!r}, '
                f'signer_instruction_id={(self.signer_instruction_id if hasattr(self, "signer_instruction_id") else None)!r}, '
                f'confirmation_instruction_id={(self.confirmation_instruction_id if hasattr(self, "confirmation_instruction_id") else None)!r}, '
                f'theme_color={(self.theme_color if hasattr(self, "theme_color") else None)!r}, '
                f'session_expire={(self.session_expire if hasattr(self, "session_expire") else None)!r}, '
                f'expiry={(self.expiry if hasattr(self, "expiry") else None)!r}, '
                f'sender_email={(self.sender_email if hasattr(self, "sender_email") else None)!r}, '
                f'create_executed_folder={(self.create_executed_folder if hasattr(self, "create_executed_folder") else None)!r}, '
                f'hide_field_name_for_recipients={(self.hide_field_name_for_recipients if hasattr(self, "hide_field_name_for_recipients") else None)!r}, '
                f'hide_checkbox_border={(self.hide_checkbox_border if hasattr(self, "hide_checkbox_border") else None)!r}, '
                f'hide_decline_to_sign={(self.hide_decline_to_sign if hasattr(self, "hide_decline_to_sign") else None)!r}, '
                f'hide_more_action={(self.hide_more_action if hasattr(self, "hide_more_action") else None)!r}, '
                f'hide_next_required_fieldbtn={(self.hide_next_required_fieldbtn if hasattr(self, "hide_next_required_fieldbtn") else None)!r}, '
                f'folder_password={(self.folder_password if hasattr(self, "folder_password") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'folder_id={self.folder_id!s}, '
                f'folder_name={self.folder_name!s}, '
                f'parties={self.parties!s}, '
                f'sign_in_sequence={(self.sign_in_sequence if hasattr(self, "sign_in_sequence") else None)!s}, '
                f'in_person_enable={(self.in_person_enable if hasattr(self, "in_person_enable") else None)!s}, '
                f'fields={(self.fields if hasattr(self, "fields") else None)!s}, '
                f'send_now={(self.send_now if hasattr(self, "send_now") else None)!s}, '
                f'create_embedded_signing_session={(self.create_embedded_signing_session if hasattr(self, "create_embedded_signing_session") else None)!s}, '
                f'embedded_signers_email_ids={(self.embedded_signers_email_ids if hasattr(self, "embedded_signers_email_ids") else None)!s}, '
                f'custom_field_1={(self.custom_field_1 if hasattr(self, "custom_field_1") else None)!s}, '
                f'sign_success_url={(self.sign_success_url if hasattr(self, "sign_success_url") else None)!s}, '
                f'sign_decline_url={(self.sign_decline_url if hasattr(self, "sign_decline_url") else None)!s}, '
                f'sign_later_url={(self.sign_later_url if hasattr(self, "sign_later_url") else None)!s}, '
                f'sign_error_url={(self.sign_error_url if hasattr(self, "sign_error_url") else None)!s}, '
                f'allow_send_now_and_embedded_signing_session={(self.allow_send_now_and_embedded_signing_session if hasattr(self, "allow_send_now_and_embedded_signing_session") else None)!s}, '
                f'allow_advanced_email_validation={(self.allow_advanced_email_validation if hasattr(self, "allow_advanced_email_validation") else None)!s}, '
                f'sign_success_url_all_parties={(self.sign_success_url_all_parties if hasattr(self, "sign_success_url_all_parties") else None)!s}, '
                f'email_template_id={(self.email_template_id if hasattr(self, "email_template_id") else None)!s}, '
                f'signer_instruction_id={(self.signer_instruction_id if hasattr(self, "signer_instruction_id") else None)!s}, '
                f'confirmation_instruction_id={(self.confirmation_instruction_id if hasattr(self, "confirmation_instruction_id") else None)!s}, '
                f'theme_color={(self.theme_color if hasattr(self, "theme_color") else None)!s}, '
                f'session_expire={(self.session_expire if hasattr(self, "session_expire") else None)!s}, '
                f'expiry={(self.expiry if hasattr(self, "expiry") else None)!s}, '
                f'sender_email={(self.sender_email if hasattr(self, "sender_email") else None)!s}, '
                f'create_executed_folder={(self.create_executed_folder if hasattr(self, "create_executed_folder") else None)!s}, '
                f'hide_field_name_for_recipients={(self.hide_field_name_for_recipients if hasattr(self, "hide_field_name_for_recipients") else None)!s}, '
                f'hide_checkbox_border={(self.hide_checkbox_border if hasattr(self, "hide_checkbox_border") else None)!s}, '
                f'hide_decline_to_sign={(self.hide_decline_to_sign if hasattr(self, "hide_decline_to_sign") else None)!s}, '
                f'hide_more_action={(self.hide_more_action if hasattr(self, "hide_more_action") else None)!s}, '
                f'hide_next_required_fieldbtn={(self.hide_next_required_fieldbtn if hasattr(self, "hide_next_required_fieldbtn") else None)!s}, '
                f'folder_password={(self.folder_password if hasattr(self, "folder_password") else None)!s})')
