"""reportingapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from reportingapi.api_helper import APIHelper
from reportingapi.models.date_range_search import (
    DateRangeSearch,
)
from reportingapi.models.entity_list_type_super_chain import (
    EntityListTypeSuperChain,
)
from reportingapi.models.pagination_type_1 import (
    PaginationType1,
)


class DepositSummarySuperChainRequest(object):
    """Implementation of the 'DepositSummarySuperChainRequest' model.

    Attributes:
        pagination (PaginationType1): Used for pagination.
        hierarchy (EntityListTypeSuperChain): Refers to merchant hierarchy
            levels
        date_range (DateRangeSearch): A range of dates that includes a
            particular start and end date and all dates in between the range.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "hierarchy": "hierarchy",
        "date_range": "dateRange",
        "pagination": "pagination",
    }

    _optionals = [
        "pagination",
    ]

    def __init__(self,
                 hierarchy=None,
                 date_range=None,
                 pagination=APIHelper.SKIP):
        """Initialize a DepositSummarySuperChainRequest instance."""
        # Initialize members of the class
        if pagination is not APIHelper.SKIP:
            self.pagination = pagination
        self.hierarchy = hierarchy
        self.date_range = date_range

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        hierarchy = EntityListTypeSuperChain.from_dictionary(
            dictionary.get("hierarchy"))\
            if dictionary.get("hierarchy") else None
        date_range = DateRangeSearch.from_dictionary(
            dictionary.get("dateRange"))\
            if dictionary.get("dateRange") else None
        pagination = PaginationType1.from_dictionary(
            dictionary.get("pagination"))\
            if "pagination" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(hierarchy,
                   date_range,
                   pagination)

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"pagination={(self.pagination
                     if hasattr(self, 'pagination') else None)!r}, "
                f"hierarchy={self.hierarchy!r}, "
                f"date_range={self.date_range!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"pagination={(self.pagination
                     if hasattr(self, 'pagination') else None)!s}, "
                f"hierarchy={self.hierarchy!s}, "
                f"date_range={self.date_range!s})")
