"""reportingapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from reportingapi.api_helper import APIHelper
from reportingapi.models.code_and_description_1 import (
    CodeAndDescription1,
)


class RealGiftMerchantHierarchyDetails(object):
    """Implementation of the 'RealGiftMerchantHierarchyDetails' model.

    Resource is used to retrieve gift transaction details for real time.

    Attributes:
        chain_code (str): The Chain Code is the level of the merchant
            hierarchy that groups merchant identifiers (MIDs) and any related
            roll-up values under a common identifier for settlement, billing
            and reporting. Chain Code is the primary identifier for merchants
            boarded in MDB (Merchant Database) system.
        division_number (str): The Division Number is a hierarchy level that
            enables merchants to roll-up child entities for Stores / Locations
            into different groups under a Chain. The Division Code is an
            optional hierarchy level but if created, is required for all child
            entities under the Division Number.
        store_number (str): The Store/Location Code is the lowest roll-up
            level in the hierarchy system, grouping multiple merchant account
            numbers (MIDs) used in a single merchant location. The Store/
            Locations are used to link multiple merchant numbers assigned to
            different terminals and/or business lines (MCC’s).
        merchant_id (str): The Merchant hierarchy level is the last level in
            the Vertical Hierarchy. MID is the unique identifier assigned for
            a processing location, business type, MCC Code that requires a
            specific value to define merchant authorizations, settlement,
            reporting, pricing and billing levels.
        merchant_name (str): Merchant Name refers to the name registered for
            businesses.
        clerk_id (str): Indicates id of clerk
        mcc_code (str): Merchant category codes (MCCs) are four-digit numbers
            that describe a merchant's primary business activities.
        terminal_capability (CodeAndDescription1): Refers to the code of
            terminal capabilities.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "chain_code": "chainCode",
        "division_number": "divisionNumber",
        "store_number": "storeNumber",
        "merchant_id": "merchantId",
        "merchant_name": "merchantName",
        "clerk_id": "clerkId",
        "mcc_code": "mccCode",
        "terminal_capability": "terminalCapability",
    }

    _optionals = [
        "chain_code",
        "division_number",
        "store_number",
        "merchant_id",
        "merchant_name",
        "clerk_id",
        "mcc_code",
        "terminal_capability",
    ]

    def __init__(self,
                 chain_code=APIHelper.SKIP,
                 division_number=APIHelper.SKIP,
                 store_number=APIHelper.SKIP,
                 merchant_id=APIHelper.SKIP,
                 merchant_name=APIHelper.SKIP,
                 clerk_id=APIHelper.SKIP,
                 mcc_code=APIHelper.SKIP,
                 terminal_capability=APIHelper.SKIP):
        """Initialize a RealGiftMerchantHierarchyDetails instance."""
        # Initialize members of the class
        if chain_code is not APIHelper.SKIP:
            self.chain_code = chain_code
        if division_number is not APIHelper.SKIP:
            self.division_number = division_number
        if store_number is not APIHelper.SKIP:
            self.store_number = store_number
        if merchant_id is not APIHelper.SKIP:
            self.merchant_id = merchant_id
        if merchant_name is not APIHelper.SKIP:
            self.merchant_name = merchant_name
        if clerk_id is not APIHelper.SKIP:
            self.clerk_id = clerk_id
        if mcc_code is not APIHelper.SKIP:
            self.mcc_code = mcc_code
        if terminal_capability is not APIHelper.SKIP:
            self.terminal_capability = terminal_capability

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        chain_code =\
            dictionary.get("chainCode")\
            if dictionary.get("chainCode") else APIHelper.SKIP
        division_number =\
            dictionary.get("divisionNumber")\
            if dictionary.get("divisionNumber") else APIHelper.SKIP
        store_number =\
            dictionary.get("storeNumber")\
            if dictionary.get("storeNumber") else APIHelper.SKIP
        merchant_id =\
            dictionary.get("merchantId")\
            if dictionary.get("merchantId") else APIHelper.SKIP
        merchant_name =\
            dictionary.get("merchantName")\
            if dictionary.get("merchantName") else APIHelper.SKIP
        clerk_id =\
            dictionary.get("clerkId")\
            if dictionary.get("clerkId") else APIHelper.SKIP
        mcc_code =\
            dictionary.get("mccCode")\
            if dictionary.get("mccCode") else APIHelper.SKIP
        terminal_capability = CodeAndDescription1.from_dictionary(
            dictionary.get("terminalCapability"))\
            if "terminalCapability" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(chain_code,
                   division_number,
                   store_number,
                   merchant_id,
                   merchant_name,
                   clerk_id,
                   mcc_code,
                   terminal_capability)

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"chain_code={(self.chain_code
                     if hasattr(self, 'chain_code') else None)!r}, "
                f"division_number={(self.division_number
                     if hasattr(self, 'division_number') else None)!r}, "
                f"store_number={(self.store_number
                     if hasattr(self, 'store_number') else None)!r}, "
                f"merchant_id={(self.merchant_id
                     if hasattr(self, 'merchant_id') else None)!r}, "
                f"merchant_name={(self.merchant_name
                     if hasattr(self, 'merchant_name') else None)!r}, "
                f"clerk_id={(self.clerk_id
                     if hasattr(self, 'clerk_id') else None)!r}, "
                f"mcc_code={(self.mcc_code
                     if hasattr(self, 'mcc_code') else None)!r}, "
                f"terminal_capability={(self.terminal_capability
                     if hasattr(self, 'terminal_capability') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"chain_code={(self.chain_code
                     if hasattr(self, 'chain_code') else None)!s}, "
                f"division_number={(self.division_number
                     if hasattr(self, 'division_number') else None)!s}, "
                f"store_number={(self.store_number
                     if hasattr(self, 'store_number') else None)!s}, "
                f"merchant_id={(self.merchant_id
                     if hasattr(self, 'merchant_id') else None)!s}, "
                f"merchant_name={(self.merchant_name
                     if hasattr(self, 'merchant_name') else None)!s}, "
                f"clerk_id={(self.clerk_id
                     if hasattr(self, 'clerk_id') else None)!s}, "
                f"mcc_code={(self.mcc_code
                     if hasattr(self, 'mcc_code') else None)!s}, "
                f"terminal_capability={(self.terminal_capability
                     if hasattr(self, 'terminal_capability') else None)!s})")
