"""reportingapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from reportingapi.api_helper import APIHelper
from reportingapi.models.summary_verticals_inner import (
    SummaryVerticalsInner,
)


class SummaryVerticals(object):
    """Implementation of the 'SummaryVerticals' model.

    Summary for verticals.

    Attributes:
        summaries (List[SummaryVerticalsInner]): Summary details

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "summaries": "summaries",
    }

    _optionals = [
        "summaries",
    ]

    def __init__(self,
                 summaries=APIHelper.SKIP):
        """Initialize a SummaryVerticals instance."""
        # Initialize members of the class
        if summaries is not APIHelper.SKIP:
            self.summaries = summaries

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        summaries = None
        if dictionary.get("summaries") is not None:
            summaries = [
                SummaryVerticalsInner.from_dictionary(x)
                    for x in dictionary.get("summaries")
            ]
        else:
            summaries = APIHelper.SKIP
        # Return an object of this model
        return cls(summaries)

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"summaries={(self.summaries
                     if hasattr(self, 'summaries') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"summaries={(self.summaries
                     if hasattr(self, 'summaries') else None)!s})")
