# -*- coding: utf-8 -*-

"""
multiplesimilarauthtypes

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os
from apimatic_core.authentication.query_auth import QueryAuth


class HttpQuery(QueryAuth):

    @property
    def error_message(self):
        """Display error message on occurrence of authentication failure
        in HttpQuery

        """
        return "HttpQuery: token or api-key is undefined."

    def __init__(self, http_query_credentials):
        auth_params = {}
        if http_query_credentials is not None \
                and http_query_credentials.token is not None:
            auth_params["token"] = http_query_credentials.token
        if http_query_credentials is not None \
                and http_query_credentials.api_key is not None:
            auth_params["api-key"] = http_query_credentials.api_key
        super().__init__(auth_params=auth_params)


class HttpQueryCredentials:

    @property
    def token(self):
        return self._token

    @property
    def api_key(self):
        return self._api_key

    def __init__(self, token, api_key):
        if token is None:
            raise ValueError('token cannot be None')
        if api_key is None:
            raise ValueError('api_key cannot be None')
        self._token = token
        self._api_key = api_key

    def clone_with(self, token=None, api_key=None):
        return HttpQueryCredentials(token or self.token,
                                    api_key or self.api_key)

    @classmethod
    def from_environment(cls):
        token = os.getenv('HTTP_QUERY_TOKEN', None)
        api_key = os.getenv('HTTP_QUERY_API_KEY', None)

        if token is None or api_key is None:
            return None

        return cls(
            token=token,
            api_key=api_key
        )