
"""
allowadditionalenumitemsapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

# ruff: noqa: PLR0915, W291
from tests.controllers.controller_test_base import (
    ControllerTestBase,
)


class APIControllerTests(ControllerTestBase):
    """
    Endpoint tests for validating the API behavior.

    Ensures controller methods execute correctly and produce the expected
    responses using the shared test client and response catcher.
    """

    controller = None

    @classmethod
    def setUpClass(cls):
        """
        Initialize the shared test client and controller for all test methods.
        """
        super().setUpClass()
        cls.controller = cls.client.client
        cls.response_catcher = cls.controller.http_call_back

    def test_should_not_throw_exception_on_unexpected_enums(self):
        """
        Api call test for `test_should_not_throw_exception_on_unexpected_enums`.
        """
        # Parameters for the API call
        test_case = "getAdditionalEnums"

        # Perform the API call through the SDK function
        self.controller.get_enums(
            test_case,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200

    def test_should_not_throw_exception_on_expected_enums(self):
        """
        Api call test for `test_should_not_throw_exception_on_expected_enums`.
        """
        # Parameters for the API call
        test_case = "getExpectedEnums"

        # Perform the API call through the SDK function
        self.controller.get_enums(
            test_case,
        )
        # Test response code
        assert self.response_catcher.response.status_code == 200

