"""akoya.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""


class Iso3166CountryCode(object):
    """Implementation of the 'ISO 3166 Country Code' enum.

    Country code

    Attributes:
        AD: The enum member of type str.
        AE: The enum member of type str.
        AF: The enum member of type str.
        AG: The enum member of type str.
        AI: The enum member of type str.
        AL: The enum member of type str.
        AM: The enum member of type str.
        AO: The enum member of type str.
        AQ: The enum member of type str.
        AR: The enum member of type str.
        AS: The enum member of type str.
        AT: The enum member of type str.
        AU: The enum member of type str.
        AW: The enum member of type str.
        AX: The enum member of type str.
        AZ: The enum member of type str.
        BA: The enum member of type str.
        BB: The enum member of type str.
        BD: The enum member of type str.
        BE: The enum member of type str.
        BF: The enum member of type str.
        BG: The enum member of type str.
        BH: The enum member of type str.
        BI: The enum member of type str.
        BJ: The enum member of type str.
        BL: The enum member of type str.
        BM: The enum member of type str.
        BN: The enum member of type str.
        BO: The enum member of type str.
        BQ: The enum member of type str.
        BR: The enum member of type str.
        BS: The enum member of type str.
        BT: The enum member of type str.
        BV: The enum member of type str.
        BW: The enum member of type str.
        BY: The enum member of type str.
        BZ: The enum member of type str.
        CA: The enum member of type str.
        CC: The enum member of type str.
        CD: The enum member of type str.
        CF: The enum member of type str.
        CG: The enum member of type str.
        CH: The enum member of type str.
        CI: The enum member of type str.
        CK: The enum member of type str.
        CL: The enum member of type str.
        CM: The enum member of type str.
        CN: The enum member of type str.
        CO: The enum member of type str.
        CR: The enum member of type str.
        CU: The enum member of type str.
        CV: The enum member of type str.
        CW: The enum member of type str.
        CX: The enum member of type str.
        CY: The enum member of type str.
        CZ: The enum member of type str.
        DE: The enum member of type str.
        DJ: The enum member of type str.
        DK: The enum member of type str.
        DM: The enum member of type str.
        DO: The enum member of type str.
        DZ: The enum member of type str.
        EC: The enum member of type str.
        EE: The enum member of type str.
        EG: The enum member of type str.
        EH: The enum member of type str.
        ER: The enum member of type str.
        ES: The enum member of type str.
        ET: The enum member of type str.
        FI: The enum member of type str.
        FJ: The enum member of type str.
        FK: The enum member of type str.
        FM: The enum member of type str.
        FO: The enum member of type str.
        FR: The enum member of type str.
        GA: The enum member of type str.
        GB: The enum member of type str.
        GD: The enum member of type str.
        GE: The enum member of type str.
        GF: The enum member of type str.
        GG: The enum member of type str.
        GH: The enum member of type str.
        GI: The enum member of type str.
        GL: The enum member of type str.
        GM: The enum member of type str.
        GN: The enum member of type str.
        GP: The enum member of type str.
        GQ: The enum member of type str.
        GR: The enum member of type str.
        GS: The enum member of type str.
        GT: The enum member of type str.
        GU: The enum member of type str.
        GW: The enum member of type str.
        GY: The enum member of type str.
        HK: The enum member of type str.
        HM: The enum member of type str.
        HN: The enum member of type str.
        HR: The enum member of type str.
        HT: The enum member of type str.
        HU: The enum member of type str.
        ID: The enum member of type str.
        IE: The enum member of type str.
        IL: The enum member of type str.
        IM: The enum member of type str.
        IN: The enum member of type str.
        IO: The enum member of type str.
        IQ: The enum member of type str.
        IR: The enum member of type str.
        IS: The enum member of type str.
        IT: The enum member of type str.
        JE: The enum member of type str.
        JM: The enum member of type str.
        JO: The enum member of type str.
        JP: The enum member of type str.
        KE: The enum member of type str.
        KG: The enum member of type str.
        KH: The enum member of type str.
        KI: The enum member of type str.
        KM: The enum member of type str.
        KN: The enum member of type str.
        KP: The enum member of type str.
        KR: The enum member of type str.
        KW: The enum member of type str.
        KY: The enum member of type str.
        KZ: The enum member of type str.
        LA: The enum member of type str.
        LB: The enum member of type str.
        LC: The enum member of type str.
        LI: The enum member of type str.
        LK: The enum member of type str.
        LR: The enum member of type str.
        LS: The enum member of type str.
        LT: The enum member of type str.
        LU: The enum member of type str.
        LV: The enum member of type str.
        LY: The enum member of type str.
        MA: The enum member of type str.
        MC: The enum member of type str.
        MD: The enum member of type str.
        ME: The enum member of type str.
        MF: The enum member of type str.
        MG: The enum member of type str.
        MH: The enum member of type str.
        MK: The enum member of type str.
        ML: The enum member of type str.
        MM: The enum member of type str.
        MN: The enum member of type str.
        MO: The enum member of type str.
        MP: The enum member of type str.
        MQ: The enum member of type str.
        MR: The enum member of type str.
        MS: The enum member of type str.
        MT: The enum member of type str.
        MU: The enum member of type str.
        MV: The enum member of type str.
        MW: The enum member of type str.
        MX: The enum member of type str.
        MY: The enum member of type str.
        MZ: The enum member of type str.
        NA: The enum member of type str.
        NC: The enum member of type str.
        NE: The enum member of type str.
        NF: The enum member of type str.
        NG: The enum member of type str.
        NI: The enum member of type str.
        NL: The enum member of type str.
        NO: The enum member of type str.
        NP: The enum member of type str.
        NR: The enum member of type str.
        NU: The enum member of type str.
        NZ: The enum member of type str.
        OM: The enum member of type str.
        PA: The enum member of type str.
        PE: The enum member of type str.
        PF: The enum member of type str.
        PG: The enum member of type str.
        PH: The enum member of type str.
        PK: The enum member of type str.
        PL: The enum member of type str.
        PM: The enum member of type str.
        PN: The enum member of type str.
        PR: The enum member of type str.
        PS: The enum member of type str.
        PT: The enum member of type str.
        PW: The enum member of type str.
        PY: The enum member of type str.
        QA: The enum member of type str.
        RE: The enum member of type str.
        RO: The enum member of type str.
        RS: The enum member of type str.
        RU: The enum member of type str.
        RW: The enum member of type str.
        SA: The enum member of type str.
        SB: The enum member of type str.
        SC: The enum member of type str.
        SD: The enum member of type str.
        SE: The enum member of type str.
        SG: The enum member of type str.
        SH: The enum member of type str.
        SI: The enum member of type str.
        SJ: The enum member of type str.
        SK: The enum member of type str.
        SL: The enum member of type str.
        SM: The enum member of type str.
        SN: The enum member of type str.
        SO: The enum member of type str.
        SR: The enum member of type str.
        SS: The enum member of type str.
        ST: The enum member of type str.
        SV: The enum member of type str.
        SX: The enum member of type str.
        SY: The enum member of type str.
        SZ: The enum member of type str.
        TC: The enum member of type str.
        TD: The enum member of type str.
        TF: The enum member of type str.
        TG: The enum member of type str.
        TH: The enum member of type str.
        TJ: The enum member of type str.
        TK: The enum member of type str.
        TL: The enum member of type str.
        TM: The enum member of type str.
        TN: The enum member of type str.
        TO: The enum member of type str.
        TR: The enum member of type str.
        TT: The enum member of type str.
        TV: The enum member of type str.
        TW: The enum member of type str.
        TZ: The enum member of type str.
        UA: The enum member of type str.
        UG: The enum member of type str.
        UM: The enum member of type str.
        US: The enum member of type str.
        UY: The enum member of type str.
        UZ: The enum member of type str.
        VA: The enum member of type str.
        VC: The enum member of type str.
        VE: The enum member of type str.
        VG: The enum member of type str.
        VI: The enum member of type str.
        VN: The enum member of type str.
        VU: The enum member of type str.
        WF: The enum member of type str.
        WS: The enum member of type str.
        YE: The enum member of type str.
        YT: The enum member of type str.
        ZA: The enum member of type str.
        ZM: The enum member of type str.
        ZW: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """

    AD = "AD"

    AE = "AE"

    AF = "AF"

    AG = "AG"

    AI = "AI"

    AL = "AL"

    AM = "AM"

    AO = "AO"

    AQ = "AQ"

    AR = "AR"

    AS = "AS"

    AT = "AT"

    AU = "AU"

    AW = "AW"

    AX = "AX"

    AZ = "AZ"

    BA = "BA"

    BB = "BB"

    BD = "BD"

    BE = "BE"

    BF = "BF"

    BG = "BG"

    BH = "BH"

    BI = "BI"

    BJ = "BJ"

    BL = "BL"

    BM = "BM"

    BN = "BN"

    BO = "BO"

    BQ = "BQ"

    BR = "BR"

    BS = "BS"

    BT = "BT"

    BV = "BV"

    BW = "BW"

    BY = "BY"

    BZ = "BZ"

    CA = "CA"

    CC = "CC"

    CD = "CD"

    CF = "CF"

    CG = "CG"

    CH = "CH"

    CI = "CI"

    CK = "CK"

    CL = "CL"

    CM = "CM"

    CN = "CN"

    CO = "CO"

    CR = "CR"

    CU = "CU"

    CV = "CV"

    CW = "CW"

    CX = "CX"

    CY = "CY"

    CZ = "CZ"

    DE = "DE"

    DJ = "DJ"

    DK = "DK"

    DM = "DM"

    DO = "DO"

    DZ = "DZ"

    EC = "EC"

    EE = "EE"

    EG = "EG"

    EH = "EH"

    ER = "ER"

    ES = "ES"

    ET = "ET"

    FI = "FI"

    FJ = "FJ"

    FK = "FK"

    FM = "FM"

    FO = "FO"

    FR = "FR"

    GA = "GA"

    GB = "GB"

    GD = "GD"

    GE = "GE"

    GF = "GF"

    GG = "GG"

    GH = "GH"

    GI = "GI"

    GL = "GL"

    GM = "GM"

    GN = "GN"

    GP = "GP"

    GQ = "GQ"

    GR = "GR"

    GS = "GS"

    GT = "GT"

    GU = "GU"

    GW = "GW"

    GY = "GY"

    HK = "HK"

    HM = "HM"

    HN = "HN"

    HR = "HR"

    HT = "HT"

    HU = "HU"

    ID = "ID"

    IE = "IE"

    IL = "IL"

    IM = "IM"

    IN = "IN"

    IO = "IO"

    IQ = "IQ"

    IR = "IR"

    IS = "IS"

    IT = "IT"

    JE = "JE"

    JM = "JM"

    JO = "JO"

    JP = "JP"

    KE = "KE"

    KG = "KG"

    KH = "KH"

    KI = "KI"

    KM = "KM"

    KN = "KN"

    KP = "KP"

    KR = "KR"

    KW = "KW"

    KY = "KY"

    KZ = "KZ"

    LA = "LA"

    LB = "LB"

    LC = "LC"

    LI = "LI"

    LK = "LK"

    LR = "LR"

    LS = "LS"

    LT = "LT"

    LU = "LU"

    LV = "LV"

    LY = "LY"

    MA = "MA"

    MC = "MC"

    MD = "MD"

    ME = "ME"

    MF = "MF"

    MG = "MG"

    MH = "MH"

    MK = "MK"

    ML = "ML"

    MM = "MM"

    MN = "MN"

    MO = "MO"

    MP = "MP"

    MQ = "MQ"

    MR = "MR"

    MS = "MS"

    MT = "MT"

    MU = "MU"

    MV = "MV"

    MW = "MW"

    MX = "MX"

    MY = "MY"

    MZ = "MZ"

    NA = "NA"

    NC = "NC"

    NE = "NE"

    NF = "NF"

    NG = "NG"

    NI = "NI"

    NL = "NL"

    NO = "NO"

    NP = "NP"

    NR = "NR"

    NU = "NU"

    NZ = "NZ"

    OM = "OM"

    PA = "PA"

    PE = "PE"

    PF = "PF"

    PG = "PG"

    PH = "PH"

    PK = "PK"

    PL = "PL"

    PM = "PM"

    PN = "PN"

    PR = "PR"

    PS = "PS"

    PT = "PT"

    PW = "PW"

    PY = "PY"

    QA = "QA"

    RE = "RE"

    RO = "RO"

    RS = "RS"

    RU = "RU"

    RW = "RW"

    SA = "SA"

    SB = "SB"

    SC = "SC"

    SD = "SD"

    SE = "SE"

    SG = "SG"

    SH = "SH"

    SI = "SI"

    SJ = "SJ"

    SK = "SK"

    SL = "SL"

    SM = "SM"

    SN = "SN"

    SO = "SO"

    SR = "SR"

    SS = "SS"

    ST = "ST"

    SV = "SV"

    SX = "SX"

    SY = "SY"

    SZ = "SZ"

    TC = "TC"

    TD = "TD"

    TF = "TF"

    TG = "TG"

    TH = "TH"

    TJ = "TJ"

    TK = "TK"

    TL = "TL"

    TM = "TM"

    TN = "TN"

    TO = "TO"

    TR = "TR"

    TT = "TT"

    TV = "TV"

    TW = "TW"

    TZ = "TZ"

    UA = "UA"

    UG = "UG"

    UM = "UM"

    US = "US"

    UY = "UY"

    UZ = "UZ"

    VA = "VA"

    VC = "VC"

    VE = "VE"

    VG = "VG"

    VI = "VI"

    VN = "VN"

    VU = "VU"

    WF = "WF"

    WS = "WS"

    YE = "YE"

    YT = "YT"

    ZA = "ZA"

    ZM = "ZM"

    ZW = "ZW"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
