# -*- coding: utf-8 -*-

"""
akoya

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TaxPartyType(object):

    """Implementation of the 'Tax Party Type' enum.

    Type of issuer or recipient legal entity, as "BUSINESS" or "INDIVIDUAL".
    Commonly BUSINESS for issuer and INDIVIDUAL for recipient

    Attributes:
        BUSINESS: The enum member of type str.
        INDIVIDUAL: The enum member of type str.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """
    BUSINESS = 'BUSINESS'

    INDIVIDUAL = 'INDIVIDUAL'

    @classmethod
    def from_value(cls, value, default=None):
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
