# -*- coding: utf-8 -*-

"""
mdnotesccgwithoutauthscopes

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import os
import unittest
from tests.http_response_catcher import HttpResponseCatcher
from mdnotesccgwithoutauthscopes.configuration import Configuration, Environment
from mdnotesccgwithoutauthscopes.mdnotesccgwithoutauthscopes_client import MdnotesccgwithoutauthscopesClient
from mdnotesccgwithoutauthscopes.http.auth.o_auth_2 import ClientCredentialsAuthCredentials


class ControllerTestBase(unittest.TestCase):

    """All test classes inherit from this base class. It abstracts out
    common functionality and configuration variables set up."""

    client = None
    config = None

    @classmethod
    def setUpClass(cls):
        """Class method called once before running tests in a test class."""
        cls.request_timeout = 30
        cls.assert_precision = 0.01
        cls.config = ControllerTestBase.create_configuration()
        cls.client = MdnotesccgwithoutauthscopesClient(config=cls.config)

    @staticmethod
    def create_configuration():
        return Configuration.from_environment(
            client_credentials_auth_credentials=ClientCredentialsAuthCredentials(
                o_auth_client_id='23',
                o_auth_client_secret='tQNSqQlXBIwZcY9auoujQ57ckDcoh3t8UPbBRkSF'),
            http_call_back=HttpResponseCatcher())
