# -*- coding: utf-8 -*-

"""
mindbodypublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mindbodypublicapi.api_helper import APIHelper


class AssignedClientIndex(object):

    """Implementation of the 'AssignedClientIndex' model.

    Represents a client index value assigned to a client

    Attributes:
        id (int): The index ID assigned to the client.
        value_id (int): The index’s value ID.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'Id',
        "value_id": 'ValueId'
    }

    _optionals = [
        'id',
        'value_id',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 value_id=APIHelper.SKIP):
        """Constructor for the AssignedClientIndex class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if value_id is not APIHelper.SKIP:
            self.value_id = value_id 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("Id") if dictionary.get("Id") else APIHelper.SKIP
        value_id = dictionary.get("ValueId") if dictionary.get("ValueId") else APIHelper.SKIP
        # Return an object of this model
        return cls(id,
                   value_id)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!r}, '
                f'value_id={(self.value_id if hasattr(self, "value_id") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!s}, '
                f'value_id={(self.value_id if hasattr(self, "value_id") else None)!s})')
