"""mindbodypublicapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from mindbodypublicapi.api_helper import APIHelper


class GetClientReferralTypesResponse(object):
    """Implementation of the 'GetClientReferralTypesResponse' model.

    Attributes:
        referral_types (List[str]): The list of available referral types.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "referral_types": "ReferralTypes",
    }

    _optionals = [
        "referral_types",
    ]

    def __init__(self,
                 referral_types=APIHelper.SKIP):
        """Initialize a GetClientReferralTypesResponse instance."""
        # Initialize members of the class
        if referral_types is not APIHelper.SKIP:
            self.referral_types = referral_types

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        referral_types =\
            dictionary.get("ReferralTypes")\
            if dictionary.get("ReferralTypes") else APIHelper.SKIP
        # Return an object of this model
        return cls(referral_types)

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"referral_types={(self.referral_types
                     if hasattr(self, 'referral_types') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"referral_types={(self.referral_types
                     if hasattr(self, 'referral_types') else None)!s})")
