"""mindbodypublicapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from mindbodypublicapi.api_helper import APIHelper
from mindbodypublicapi.models.m_0_culture_neutral_public_key_token_b_77_a_5_c_561934_e_089 import (  # noqa: E501
    M0CultureNeutralPublicKeyTokenB77a5c561934e089,
)


class HttpContent(object):
    """Implementation of the 'HttpContent' model.

    Attributes:
        headers (List[M0CultureNeutralPublicKeyTokenB77a5c561934e089]): The
            model property of type
            List[M0CultureNeutralPublicKeyTokenB77a5c561934e089].

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "headers": "Headers",
    }

    _optionals = [
        "headers",
    ]

    def __init__(self,
                 headers=APIHelper.SKIP):
        """Initialize a HttpContent instance."""
        # Initialize members of the class
        if headers is not APIHelper.SKIP:
            self.headers = headers

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        headers = None
        if dictionary.get("Headers") is not None:
            headers = [
                M0CultureNeutralPublicKeyTokenB77a5c561934e089.from_dictionary(x)
                    for x in dictionary.get("Headers")
            ]
        else:
            headers = APIHelper.SKIP
        # Return an object of this model
        return cls(headers)

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"headers={(self.headers
                     if hasattr(self, 'headers') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"headers={(self.headers
                     if hasattr(self, 'headers') else None)!s})")
