# -*- coding: utf-8 -*-

"""
mindbodypublicapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from mindbodypublicapi.api_helper import APIHelper
from mindbodypublicapi.models.mclass import Class


class RemoveClientFromClassResponse(object):

    """Implementation of the 'RemoveClientFromClassResponse' model.

    Attributes:
        mclass (Class): Represents a single class instance. The class meets at
            the start time, goes until the end time.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "mclass": 'Class'
    }

    _optionals = [
        'mclass',
    ]

    def __init__(self,
                 mclass=APIHelper.SKIP):
        """Constructor for the RemoveClientFromClassResponse class"""

        # Initialize members of the class
        if mclass is not APIHelper.SKIP:
            self.mclass = mclass 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        mclass = Class.from_dictionary(dictionary.get('Class')) if 'Class' in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(mclass)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'mclass={(self.mclass if hasattr(self, "mclass") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'mclass={(self.mclass if hasattr(self, "mclass") else None)!s})')
