# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from payrix.api_helper import APIHelper


class EntityRefsResponse(object):

    """Implementation of the 'entityRefsResponse' model.

    Attributes:
        id (str): The ID of this resource.
        created (str): The date and time at which this resource was created.
            The format should be YYYY-MM-DD HH:MM:SS.SSSS
        modified (str): The date and time at which this resource was modified.
            The format should be YYYY-MM-DD HH:MM:SS.SSSS
        creator (str | LoginsResponse | None): The model property of type str
            | LoginsResponse | None.
        modifier (str): The identifier of the Login that last modified this
            resource.
        entity (str): The identifier of the Entity that owns this entityRefs
            resource.
        member (str): The identifier of the Member associated with this
            entityRefs resource.
        entity_route (str): The original 'entity_route' that routed the
            merchant onto the platform which then returned this reference
            information, if applicable
        ref (str): The reference code itself.  This field is stored as a text
            string and must be between 0 and 50 characters long.
        stage (EntityRefStageEnum): An indicator showing what this terminalRef
            refers to.  <details> <summary>Valid Values</summary>  -
            `amexCharge` - **Amex Charge.** - `batch` - **Batch.** -
            `batchSuffix` - **Batch Suffix.** - `boarding` - **Boarding.** -
            `chain` - **The store chain ID for this Merchant.** - `chargeback`
            - **Chargeback.** - `companyDebit` - **Company Debit.** -
            `companyCredit` - **Company Credit.** - `create` - **Terminal
            Creation.** - `disbursement` - **Disbursement.** - `entity` -
            **The Entity ID.** - `batchFile` - **Batch File.** - `payoutFile`
            - **Payout File.** - `frontend` - **Frontend.** - `funding` -
            **The Payout funding ID for this Merchant.** - `member` - **The
            member ID for this Member.** - `merchant` - **The Merchant ID.** -
            `mid` - **The transaction Merchant ID (MID).** - `origId` -
            **Original ID.** - `store` - **The store ID for this Merchant.** -
            `software` - **Software.** - `terminal` - **Terminal.** -
            `displayName` - **Display Name.** - `domain` - **Domain.** -
            `expressCreds` - **Express Credentials.**  </details>
        staging (StagingEnum): Allows a merchant to transact under the Staging
            environment while boarding is in progress, and allows for
            configuration with valid values such as **Disabled** or
            **Enabled**.  <details> <summary>Valid Values</summary>  - `0` -
            **Disabled** - `1` - **Enabled**  </details>
        platform (EntityPlatformEnum): The processor that issued this
            terminalTxnRef.  <details> <summary>Valid Values</summary>  -
            `APPLE` - **APPLE** - `ELAVON` - **ELAVON** - `FIRSTDATA` -
            **FIRSTDATA** - `GOOGLE` - **GOOGLE** - `VANTIV` - **VANTIV** -
            `VCORE` - **VCORE** - `WELLSACH` - **WELLSACH** - `WELLSFARGO` -
            **WELLSFARGO** - `WFSINGLE` - **WFSINGLE** - `WORLDPAY` -
            **WORLDPAY** - `TDBANKCA` - **TDBANKCA**  </details>
        currency (CurrencyEnum): The currency of the entityRef. See <a
            href="https://www.iban.com/currency-codes"
            target="_blank">Currency codes</a>  for all valid values.
        funding_currency (FundingCurrencyEnum): The currency for which this
            entityRefs resource was funded on. See <a
            href="https://www.iban.com/currency-codes"
            target="_blank">Currency codes</a>  for all valid values.
        options (str): A string-JSON of options for this reference value.
        default (EntityRefsDefaultEnum): Whether this entityRef is the default
            one. Default entityRefs will have priority when processing
            transactions with no MID or Platform set.  <details>
            <summary>Valid Values</summary>  - `0` - **Not default** - `1` -
            **Default**  </details>
        fbo (str): The FBO from which this entity refers to.
        inactive (InactiveEnum): Whether this resource is marked as inactive. 
            <details> <summary>Valid Values</summary>  - `0` - **Active** -
            `1` - **Inactive**  </details>
        frozen (FrozenEnum): Whether this resource is marked as frozen. 
            <details> <summary>Valid Values</summary>  - `0` - **Not Frozen**
            - `1` - **Frozen**  </details>

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "created": 'created',
        "modified": 'modified',
        "creator": 'creator',
        "modifier": 'modifier',
        "entity": 'entity',
        "member": 'member',
        "entity_route": 'entityRoute',
        "ref": 'ref',
        "stage": 'stage',
        "staging": 'staging',
        "platform": 'platform',
        "currency": 'currency',
        "funding_currency": 'fundingCurrency',
        "options": 'options',
        "default": 'default',
        "fbo": 'fbo',
        "inactive": 'inactive',
        "frozen": 'frozen'
    }

    _optionals = [
        'id',
        'created',
        'modified',
        'creator',
        'modifier',
        'entity',
        'member',
        'entity_route',
        'ref',
        'stage',
        'staging',
        'platform',
        'currency',
        'funding_currency',
        'options',
        'default',
        'fbo',
        'inactive',
        'frozen',
    ]

    _nullables = [
        'currency',
        'funding_currency',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 created=APIHelper.SKIP,
                 modified=APIHelper.SKIP,
                 creator=APIHelper.SKIP,
                 modifier=APIHelper.SKIP,
                 entity=APIHelper.SKIP,
                 member=APIHelper.SKIP,
                 entity_route=APIHelper.SKIP,
                 ref=APIHelper.SKIP,
                 stage=APIHelper.SKIP,
                 staging=APIHelper.SKIP,
                 platform=APIHelper.SKIP,
                 currency=APIHelper.SKIP,
                 funding_currency=APIHelper.SKIP,
                 options=APIHelper.SKIP,
                 default=APIHelper.SKIP,
                 fbo=APIHelper.SKIP,
                 inactive=0,
                 frozen=0):
        """Constructor for the EntityRefsResponse class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if created is not APIHelper.SKIP:
            self.created = created 
        if modified is not APIHelper.SKIP:
            self.modified = modified 
        if creator is not APIHelper.SKIP:
            self.creator = creator 
        if modifier is not APIHelper.SKIP:
            self.modifier = modifier 
        if entity is not APIHelper.SKIP:
            self.entity = entity 
        if member is not APIHelper.SKIP:
            self.member = member 
        if entity_route is not APIHelper.SKIP:
            self.entity_route = entity_route 
        if ref is not APIHelper.SKIP:
            self.ref = ref 
        if stage is not APIHelper.SKIP:
            self.stage = stage 
        if staging is not APIHelper.SKIP:
            self.staging = staging 
        if platform is not APIHelper.SKIP:
            self.platform = platform 
        if currency is not APIHelper.SKIP:
            self.currency = currency 
        if funding_currency is not APIHelper.SKIP:
            self.funding_currency = funding_currency 
        if options is not APIHelper.SKIP:
            self.options = options 
        if default is not APIHelper.SKIP:
            self.default = default 
        if fbo is not APIHelper.SKIP:
            self.fbo = fbo 
        self.inactive = inactive 
        self.frozen = frozen 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from payrix.utilities.union_type_lookup import UnionTypeLookUp

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        created = dictionary.get("created") if dictionary.get("created") else APIHelper.SKIP
        modified = dictionary.get("modified") if dictionary.get("modified") else APIHelper.SKIP
        creator = APIHelper.deserialize_union_type(UnionTypeLookUp.get('EntityRefsResponseCreator'), dictionary.get('creator'), False) if dictionary.get('creator') is not None else APIHelper.SKIP
        modifier = dictionary.get("modifier") if dictionary.get("modifier") else APIHelper.SKIP
        entity = dictionary.get("entity") if dictionary.get("entity") else APIHelper.SKIP
        member = dictionary.get("member") if dictionary.get("member") else APIHelper.SKIP
        entity_route = dictionary.get("entityRoute") if dictionary.get("entityRoute") else APIHelper.SKIP
        ref = dictionary.get("ref") if dictionary.get("ref") else APIHelper.SKIP
        stage = dictionary.get("stage") if dictionary.get("stage") else APIHelper.SKIP
        staging = dictionary.get("staging") if dictionary.get("staging") else APIHelper.SKIP
        platform = dictionary.get("platform") if dictionary.get("platform") else APIHelper.SKIP
        currency = dictionary.get("currency") if "currency" in dictionary.keys() else APIHelper.SKIP
        funding_currency = dictionary.get("fundingCurrency") if "fundingCurrency" in dictionary.keys() else APIHelper.SKIP
        options = dictionary.get("options") if dictionary.get("options") else APIHelper.SKIP
        default = dictionary.get("default") if dictionary.get("default") else APIHelper.SKIP
        fbo = dictionary.get("fbo") if dictionary.get("fbo") else APIHelper.SKIP
        inactive = dictionary.get("inactive") if dictionary.get("inactive") else 0
        frozen = dictionary.get("frozen") if dictionary.get("frozen") else 0
        # Return an object of this model
        return cls(id,
                   created,
                   modified,
                   creator,
                   modifier,
                   entity,
                   member,
                   entity_route,
                   ref,
                   stage,
                   staging,
                   platform,
                   currency,
                   funding_currency,
                   options,
                   default,
                   fbo,
                   inactive,
                   frozen)

    @classmethod
    def validate(cls, dictionary):
        """Validates dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """

        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!r}, '
                f'created={(self.created if hasattr(self, "created") else None)!r}, '
                f'modified={(self.modified if hasattr(self, "modified") else None)!r}, '
                f'creator={(self.creator if hasattr(self, "creator") else None)!r}, '
                f'modifier={(self.modifier if hasattr(self, "modifier") else None)!r}, '
                f'entity={(self.entity if hasattr(self, "entity") else None)!r}, '
                f'member={(self.member if hasattr(self, "member") else None)!r}, '
                f'entity_route={(self.entity_route if hasattr(self, "entity_route") else None)!r}, '
                f'ref={(self.ref if hasattr(self, "ref") else None)!r}, '
                f'stage={(self.stage if hasattr(self, "stage") else None)!r}, '
                f'staging={(self.staging if hasattr(self, "staging") else None)!r}, '
                f'platform={(self.platform if hasattr(self, "platform") else None)!r}, '
                f'currency={(self.currency if hasattr(self, "currency") else None)!r}, '
                f'funding_currency={(self.funding_currency if hasattr(self, "funding_currency") else None)!r}, '
                f'options={(self.options if hasattr(self, "options") else None)!r}, '
                f'default={(self.default if hasattr(self, "default") else None)!r}, '
                f'fbo={(self.fbo if hasattr(self, "fbo") else None)!r}, '
                f'inactive={(self.inactive if hasattr(self, "inactive") else None)!r}, '
                f'frozen={(self.frozen if hasattr(self, "frozen") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!s}, '
                f'created={(self.created if hasattr(self, "created") else None)!s}, '
                f'modified={(self.modified if hasattr(self, "modified") else None)!s}, '
                f'creator={(self.creator if hasattr(self, "creator") else None)!s}, '
                f'modifier={(self.modifier if hasattr(self, "modifier") else None)!s}, '
                f'entity={(self.entity if hasattr(self, "entity") else None)!s}, '
                f'member={(self.member if hasattr(self, "member") else None)!s}, '
                f'entity_route={(self.entity_route if hasattr(self, "entity_route") else None)!s}, '
                f'ref={(self.ref if hasattr(self, "ref") else None)!s}, '
                f'stage={(self.stage if hasattr(self, "stage") else None)!s}, '
                f'staging={(self.staging if hasattr(self, "staging") else None)!s}, '
                f'platform={(self.platform if hasattr(self, "platform") else None)!s}, '
                f'currency={(self.currency if hasattr(self, "currency") else None)!s}, '
                f'funding_currency={(self.funding_currency if hasattr(self, "funding_currency") else None)!s}, '
                f'options={(self.options if hasattr(self, "options") else None)!s}, '
                f'default={(self.default if hasattr(self, "default") else None)!s}, '
                f'fbo={(self.fbo if hasattr(self, "fbo") else None)!s}, '
                f'inactive={(self.inactive if hasattr(self, "inactive") else None)!s}, '
                f'frozen={(self.frozen if hasattr(self, "frozen") else None)!s})')
