"""payrix.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from payrix.api_helper import APIHelper


class MembersResponse(object):
    """Implementation of the 'membersResponse' model.

    Attributes:
        id (str): The ID of this resource.
        created (str): The date and time at which this resource was created.
            The format should be YYYY-MM-DD HH:MM:SS.SSSS
        modified (str): The date and time at which this resource was modified.
            The format should be YYYY-MM-DD HH:MM:SS.SSSS
        creator (str | LoginsResponse | None): The model property of type str
            | LoginsResponse | None.
        modifier (str): The identifier of the Login that last modified this
            resource.
        merchant (str): The identifier of the Merchant associated with this
            Member.
        title (str): The title that this Member holds in relation to the
            associated Merchant.  This field is stored as a text string and
            must be between 0 and 100 characters long. For example, 'CEO',
            'Owner' or 'Director of Finance'.
        first (str): The first name associated with this Member.  This field
            is stored as a text string and must be between 1 and 100
            characters long.
        middle (str): The middle name associated with this Member.  This field
            is stored as a text string and must be between 0 and 100
            characters long.
        last (str): The last name associated with this Member.  This field is
            stored as a text string and must be between 1 and 100 characters
            long.
        ssn (str): The social security number of this Member. This field is
            required if the Merchant associated with the Member is a sole
            trader.  This field is stored as a text string and must be 9
            characters long and numeric characters only.
        citizenship (CitizenshipEnum): The country of which the owner is a
            citizen.  Valid values for this field is the 3-letter ISO code for
            the country.
        dob (int): The date of birth of this Member.  The date is specified as
            an eight digit string in YYYYMMDD format, for example, '20160120'
            for January 20, 2016.
        gender (GenderEnum): The gender of this Member.  <details>
            <summary>Valid Values</summary>  - `male` - **Male**   - `female`
            - **Female**  </details>
        dl (str): The driver's license number of this Member.  This field is
            stored as a text string and must be between 0 and 15 characters
            long.
        dlstate (str): The U.S. state or Canadian province relevant to the
            address provided here. If the location is within the U.S. and
            Canada, specify the 2-character postal abbreviation for the state.
            If the location is outside of the U.S. and Canada, provide the
            full state name. This field is stored as a text string and must be
            between 2 and 100 characters long.    <details> <summary>U.S.
            States</summary>    - `AK` - **Alaska (US)**    - `AR` -
            **Arkansas (US)**    - `AL` - **Alabama (US)**    - `AZ` -
            **Arizona (US)**    - `CA` - **California (US)**    - `CO` -
            **Colorado (US)**    - `CT` - **Connecticut (US)**    - `DE` -
            **Delaware (US)**    - `FL` - **Florida (US)**    - `GA` -
            **Georgia (US)**    - `HI` - **Hawaii (US)**    - `IA` - **Iowa
            (US)**    - `ID` - **Idaho (US)**    - `IL` - **Illinois (US)**
            - `IN` - **Indiana (US)**    - `KY` - **Kentucky (US)**    - `KS`
            - **Kansas (US)**    - `LA` - **Louisiana (US)**    - `MA` -
            **Massachusetts (US)**    - `MD` - **Maryland (US)**    - `ME` -
            **Maine (US)**    - `MI` - **Michigan (US)**    - `MN` -
            **Minnesota (US)**    - `MO` - **Missouri (US)**    - `MS` -
            **Mississippi (US)**    - `MT` - **Montana (US)**    - `NC` -
            **North Carolina (US)**    - `ND` - **North Dakota (US)**    -
            `NE` - **Nebraska (US)**    - `NH` - **New Hampshire (US)**    -
            `NJ` - **New Jersey (US)**    - `NM` - **New Mexico (US)**    -
            `NV` - **Nevada (US)**    - `NY` - **New York (US)**    - `OH` -
            **Ohio (US)**    - `OK`- **Oklahoma (US)**    - `OR` - **Oregon
            (US)**    - `PA` - **Pennsylvania (US)**    - `RI` - **Rhode
            Island (US)**    - `SC`- **South Carolina (US)**    - `SD` -
            **South Dakota (US)**    - `TN` - **Tennessee (US)**    - `TX` -
            **Texas (US)**    - `UT` - **Utah (US)**    - `VA` - **Virginia
            (US)**    - `VT` - **Vermont (US)**    - `WA` - **Washington
            (US)**    - `WI` - **Wisconsin (US)**    - `WV` - **West Virginia
            (US)**    - `WY` - **Wyoming (US)**  </details>     <details>
            <summary>Canada Provinces and Territories</summary>    - `AB` -
            **Alberta (CAN)**    - `BC` - **British Columbia (CAN)**    - `MB`
            - **Manitoba (CAN)**    - `ON` - **Ontario (CAN)**    - `NS` -
            **Nova Scotia (CAN)**    - `NB` - **New Brunswick (CAN)**    -
            `NL` - **Newfoundland and Labrador (CAN)**    - `NT` - **Northwest
            Territories (CAN)**    - `NU` - **Nunavut (CAN)**    - `PE` -
            **Prince Edward Island (CAN)**    - `QC` - **Quebec (CAN)**    -
            `SK` - **Saskatchewan (CAN)**    - `YT` - **Yukon (CAN)**
            </details>
        ownership (int): The share of the Member's ownership of the associated
            Merchant, expressed in basis points.  For example, 25.3% is
            expressed as '2530'.  This field is stored as an integer and must
            be between 1 and 10000 characters long.
        email (str): The email address of this Member.  This field is stored
            as a text string and must be between 1 and 100 characters long.
        fax (str): The fax number associated with this Member.  This field is
            stored as a text string and must be between 5 and 15 characters
            long.
        phone (str): The phone number associated with this Member.  This field
            is stored as a text string and must be between 5 and 15 characters
            long.
        country (CountryEnum): The country of which the owner is a citizen.
            Valid values for this field is the 3-letter ISO code for the
            country.
        timezone (TimezoneEnum): The timezone for the address associated with
            the terminal's location.  <details> <summary>Valid
            Values</summary>    - `est` - **Eastern Standard Time**      -
            `cst` - **Central Standard Time**      - `pst` - **Pacific
            Standard Time**      - `mst` - **Mountain Daylight Time**      -
            `akst` - **Alaska Standard Time**      - `hst` - **Hawaii Standard
            Time**      - `sst` - **Samoa Standard Time**      - `chst` -
            **Chamorro Standard Time**      - `ast` - **Atlantic Standard
            Time**      - `pwt` - **Palau Time**      - `mht` - **Marshall
            Islands Time**      - `chut` - **Chuuk Time**      - `nst` -
            **Newfoundland Standard Time**  </details>
        zip (str): The ZIP code in the address associated with this Member.
            This field is stored as a text string and must be between 1 and 20
            characters long.
        state (str): The U.S. state or Canadian province relevant to the
            address provided here. If the location is within the U.S. and
            Canada, specify the 2-character postal abbreviation for the state.
            If the location is outside of the U.S. and Canada, provide the
            full state name. This field is stored as a text string and must be
            between 2 and 100 characters long.    <details> <summary>U.S.
            States</summary>    - `AK` - **Alaska (US)**    - `AR` -
            **Arkansas (US)**    - `AL` - **Alabama (US)**    - `AZ` -
            **Arizona (US)**    - `CA` - **California (US)**    - `CO` -
            **Colorado (US)**    - `CT` - **Connecticut (US)**    - `DE` -
            **Delaware (US)**    - `FL` - **Florida (US)**    - `GA` -
            **Georgia (US)**    - `HI` - **Hawaii (US)**    - `IA` - **Iowa
            (US)**    - `ID` - **Idaho (US)**    - `IL` - **Illinois (US)**
            - `IN` - **Indiana (US)**    - `KY` - **Kentucky (US)**    - `KS`
            - **Kansas (US)**    - `LA` - **Louisiana (US)**    - `MA` -
            **Massachusetts (US)**    - `MD` - **Maryland (US)**    - `ME` -
            **Maine (US)**    - `MI` - **Michigan (US)**    - `MN` -
            **Minnesota (US)**    - `MO` - **Missouri (US)**    - `MS` -
            **Mississippi (US)**    - `MT` - **Montana (US)**    - `NC` -
            **North Carolina (US)**    - `ND` - **North Dakota (US)**    -
            `NE` - **Nebraska (US)**    - `NH` - **New Hampshire (US)**    -
            `NJ` - **New Jersey (US)**    - `NM` - **New Mexico (US)**    -
            `NV` - **Nevada (US)**    - `NY` - **New York (US)**    - `OH` -
            **Ohio (US)**    - `OK`- **Oklahoma (US)**    - `OR` - **Oregon
            (US)**    - `PA` - **Pennsylvania (US)**    - `RI` - **Rhode
            Island (US)**    - `SC`- **South Carolina (US)**    - `SD` -
            **South Dakota (US)**    - `TN` - **Tennessee (US)**    - `TX` -
            **Texas (US)**    - `UT` - **Utah (US)**    - `VA` - **Virginia
            (US)**    - `VT` - **Vermont (US)**    - `WA` - **Washington
            (US)**    - `WI` - **Wisconsin (US)**    - `WV` - **West Virginia
            (US)**    - `WY` - **Wyoming (US)**  </details>     <details>
            <summary>Canada Provinces and Territories</summary>    - `AB` -
            **Alberta (CAN)**    - `BC` - **British Columbia (CAN)**    - `MB`
            - **Manitoba (CAN)**    - `ON` - **Ontario (CAN)**    - `NS` -
            **Nova Scotia (CAN)**    - `NB` - **New Brunswick (CAN)**    -
            `NL` - **Newfoundland and Labrador (CAN)**    - `NT` - **Northwest
            Territories (CAN)**    - `NU` - **Nunavut (CAN)**    - `PE` -
            **Prince Edward Island (CAN)**    - `QC` - **Quebec (CAN)**    -
            `SK` - **Saskatchewan (CAN)**    - `YT` - **Yukon (CAN)**
            </details>
        city (str): The name of the city in the address associated with this
            Member.  This field is stored as a text string and must be between
            1 and 500 characters long.
        address_2 (str): The second line of the address associated with this
            Member.  This field is stored as a text string and must be between
            1 and 500 characters long.
        address_1 (str): The first line of the address associated with this
            Member.  This field is stored as a text string and must be between
            1 and 500 characters long.
        primary (MembersPrimaryEnum): Indicates whether the Member is the
            'primary' contact for the associated Merchant. Only one Member
            associated with each Merchant can be the 'primary' Member.
            <details> <summary>Valid Values</summary>  - `0` - **Not Primary
            contact.**   - `1` - **Primary contact.**  </details>
        credit_score (int): A credit score is a three-digit number that rates
            your creditworthiness. scores range from 334 to 818.
        credit_score_date (str): Date for Credit Score. The format should be
            YYYY-MM-DD HH:MM:SS.
        significant_responsibility (SignificantResponsibilityEnum): 'A
            controlling authority', or 'Control Prong'. Includes, but is not
            limited to:    * Chief Executive Officer,      * Chief Financial
            Officer,       * Chief Operating Officer,       * Managing Member,
            * General Partner,      * President,      * Vice Presidents, or
            * An individual with significant legal authority to enter the
            Legal Entity into a commercial relationship.  <details>
            <summary>Valid Values</summary>  - `0` - **No significant
            responsibility.**   - `1` - **Significant reponsibility.**
            </details>
        politically_exposed (PoliticallyExposedEnum): This person is
            politically exposed, defined as: "persons whom through their
            prominent position or influence, is more susceptible to being
            involved in bribery or corruption."  <details> <summary>Valid
            Values</summary>  - `0` - **Not politically exposed.**   - `1` -
            **Politically exposed.**  </details>
        mailing_address_1 (str): The mailing first line of the address
            associated with this Member.  This field is stored as a text
            string and must be between 1 and 500 characters long.
        treasury_prime_roles (str): ["signer", "control_person"] Any one of
            these.
        mailing_address_2 (str): The mailing second line of the address
            associated with this Member.  This field is stored as a text
            string and must be between 1 and 500 characters long.
        mailing_city (str): The mailing name of the city in the address
            associated with this Member.  This field is stored as a text
            string and must be between 1 and 500 characters long.
        mailing_state (str): The U.S. state or Canadian province relevant to
            the address provided here. If the location is within the U.S. and
            Canada, specify the 2-character postal abbreviation for the state.
            If the location is outside of the U.S. and Canada, provide the
            full state name. This field is stored as a text string and must be
            between 2 and 100 characters long.    <details> <summary>U.S.
            States</summary>    - `AK` - **Alaska (US)**    - `AR` -
            **Arkansas (US)**    - `AL` - **Alabama (US)**    - `AZ` -
            **Arizona (US)**    - `CA` - **California (US)**    - `CO` -
            **Colorado (US)**    - `CT` - **Connecticut (US)**    - `DE` -
            **Delaware (US)**    - `FL` - **Florida (US)**    - `GA` -
            **Georgia (US)**    - `HI` - **Hawaii (US)**    - `IA` - **Iowa
            (US)**    - `ID` - **Idaho (US)**    - `IL` - **Illinois (US)**
            - `IN` - **Indiana (US)**    - `KY` - **Kentucky (US)**    - `KS`
            - **Kansas (US)**    - `LA` - **Louisiana (US)**    - `MA` -
            **Massachusetts (US)**    - `MD` - **Maryland (US)**    - `ME` -
            **Maine (US)**    - `MI` - **Michigan (US)**    - `MN` -
            **Minnesota (US)**    - `MO` - **Missouri (US)**    - `MS` -
            **Mississippi (US)**    - `MT` - **Montana (US)**    - `NC` -
            **North Carolina (US)**    - `ND` - **North Dakota (US)**    -
            `NE` - **Nebraska (US)**    - `NH` - **New Hampshire (US)**    -
            `NJ` - **New Jersey (US)**    - `NM` - **New Mexico (US)**    -
            `NV` - **Nevada (US)**    - `NY` - **New York (US)**    - `OH` -
            **Ohio (US)**    - `OK`- **Oklahoma (US)**    - `OR` - **Oregon
            (US)**    - `PA` - **Pennsylvania (US)**    - `RI` - **Rhode
            Island (US)**    - `SC`- **South Carolina (US)**    - `SD` -
            **South Dakota (US)**    - `TN` - **Tennessee (US)**    - `TX` -
            **Texas (US)**    - `UT` - **Utah (US)**    - `VA` - **Virginia
            (US)**    - `VT` - **Vermont (US)**    - `WA` - **Washington
            (US)**    - `WI` - **Wisconsin (US)**    - `WV` - **West Virginia
            (US)**    - `WY` - **Wyoming (US)**  </details>     <details>
            <summary>Canada Provinces and Territories</summary>    - `AB` -
            **Alberta (CAN)**    - `BC` - **British Columbia (CAN)**    - `MB`
            - **Manitoba (CAN)**    - `ON` - **Ontario (CAN)**    - `NS` -
            **Nova Scotia (CAN)**    - `NB` - **New Brunswick (CAN)**    -
            `NL` - **Newfoundland and Labrador (CAN)**    - `NT` - **Northwest
            Territories (CAN)**    - `NU` - **Nunavut (CAN)**    - `PE` -
            **Prince Edward Island (CAN)**    - `QC` - **Quebec (CAN)**    -
            `SK` - **Saskatchewan (CAN)**    - `YT` - **Yukon (CAN)**
            </details>
        mailing_postal_code (str): The mailing postal code in the address
            associated with this Member.  This field is stored as a text
            string and must be between 1 and 20 characters long.
        mailing_country (MailingCountryEnum): The country of which the owner
            is a citizen.  Valid values for this field is the 3-letter ISO
            code for the country.
        facilitator (str): This holds the ID of the related facilitator
            records.
        vendor (str): This holds the ID of the related vendor record.
        shareable_url (str): This is a URL that was used in the Identity
            Verification for the member. This is a gotten from identity
            verification through the integration partner.
        status (str): This is also part of the verification result from the
            third party that tracks the status of the verification process of
            the member.
        created_at (int): The timestamp when was createdAt.
        completed_at (int): The timestamp when was completedAt.
        plaid_idv_id (str): This is the integration ID for the verification
            response.
        template_id (str): This is the ID of the template used in the
            verification process of the member.
        inactive (InactiveEnum): Whether this resource is marked as inactive.
            <details> <summary>Valid Values</summary>  - `0` - **Active** -
            `1` - **Inactive**  </details>
        frozen (FrozenEnum): Whether this resource is marked as frozen.
            <details> <summary>Valid Values</summary>  - `0` - **Not Frozen**
            - `1` - **Frozen**  </details>

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "created": "created",
        "modified": "modified",
        "creator": "creator",
        "modifier": "modifier",
        "merchant": "merchant",
        "title": "title",
        "first": "first",
        "middle": "middle",
        "last": "last",
        "ssn": "ssn",
        "citizenship": "citizenship",
        "dob": "dob",
        "gender": "gender",
        "dl": "dl",
        "dlstate": "dlstate",
        "ownership": "ownership",
        "email": "email",
        "fax": "fax",
        "phone": "phone",
        "country": "country",
        "timezone": "timezone",
        "zip": "zip",
        "state": "state",
        "city": "city",
        "address_2": "address2",
        "address_1": "address1",
        "primary": "primary",
        "credit_score": "creditScore",
        "credit_score_date": "creditScoreDate",
        "significant_responsibility": "significantResponsibility",
        "politically_exposed": "politicallyExposed",
        "mailing_address_1": "mailingAddress1",
        "treasury_prime_roles": "treasuryPrimeRoles",
        "mailing_address_2": "mailingAddress2",
        "mailing_city": "mailingCity",
        "mailing_state": "mailingState",
        "mailing_postal_code": "mailingPostalCode",
        "mailing_country": "mailingCountry",
        "facilitator": "facilitator",
        "vendor": "vendor",
        "shareable_url": "shareableUrl",
        "status": "status",
        "created_at": "createdAt",
        "completed_at": "completedAt",
        "plaid_idv_id": "plaidIdvId",
        "template_id": "templateId",
        "inactive": "inactive",
        "frozen": "frozen",
    }

    _optionals = [
        "id",
        "created",
        "modified",
        "creator",
        "modifier",
        "merchant",
        "title",
        "first",
        "middle",
        "last",
        "ssn",
        "citizenship",
        "dob",
        "gender",
        "dl",
        "dlstate",
        "ownership",
        "email",
        "fax",
        "phone",
        "country",
        "timezone",
        "zip",
        "state",
        "city",
        "address_2",
        "address_1",
        "primary",
        "credit_score",
        "credit_score_date",
        "significant_responsibility",
        "politically_exposed",
        "mailing_address_1",
        "treasury_prime_roles",
        "mailing_address_2",
        "mailing_city",
        "mailing_state",
        "mailing_postal_code",
        "mailing_country",
        "facilitator",
        "vendor",
        "shareable_url",
        "status",
        "created_at",
        "completed_at",
        "plaid_idv_id",
        "template_id",
        "inactive",
        "frozen",
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 created=APIHelper.SKIP,
                 modified=APIHelper.SKIP,
                 creator=APIHelper.SKIP,
                 modifier=APIHelper.SKIP,
                 merchant=APIHelper.SKIP,
                 title=APIHelper.SKIP,
                 first=APIHelper.SKIP,
                 middle=APIHelper.SKIP,
                 last=APIHelper.SKIP,
                 ssn=APIHelper.SKIP,
                 citizenship=APIHelper.SKIP,
                 dob=APIHelper.SKIP,
                 gender=APIHelper.SKIP,
                 dl=APIHelper.SKIP,
                 dlstate=APIHelper.SKIP,
                 ownership=APIHelper.SKIP,
                 email=APIHelper.SKIP,
                 fax=APIHelper.SKIP,
                 phone=APIHelper.SKIP,
                 country=APIHelper.SKIP,
                 timezone=APIHelper.SKIP,
                 zip=APIHelper.SKIP,
                 state=APIHelper.SKIP,
                 city=APIHelper.SKIP,
                 address_2=APIHelper.SKIP,
                 address_1=APIHelper.SKIP,
                 primary=0,
                 credit_score=APIHelper.SKIP,
                 credit_score_date=APIHelper.SKIP,
                 significant_responsibility=APIHelper.SKIP,
                 politically_exposed=APIHelper.SKIP,
                 mailing_address_1=APIHelper.SKIP,
                 treasury_prime_roles=APIHelper.SKIP,
                 mailing_address_2=APIHelper.SKIP,
                 mailing_city=APIHelper.SKIP,
                 mailing_state=APIHelper.SKIP,
                 mailing_postal_code=APIHelper.SKIP,
                 mailing_country=APIHelper.SKIP,
                 facilitator=APIHelper.SKIP,
                 vendor=APIHelper.SKIP,
                 shareable_url=APIHelper.SKIP,
                 status=APIHelper.SKIP,
                 created_at=APIHelper.SKIP,
                 completed_at=APIHelper.SKIP,
                 plaid_idv_id=APIHelper.SKIP,
                 template_id=APIHelper.SKIP,
                 inactive=0,
                 frozen=0):
        """Initialize a MembersResponse instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if created is not APIHelper.SKIP:
            self.created = created
        if modified is not APIHelper.SKIP:
            self.modified = modified
        if creator is not APIHelper.SKIP:
            self.creator = creator
        if modifier is not APIHelper.SKIP:
            self.modifier = modifier
        if merchant is not APIHelper.SKIP:
            self.merchant = merchant
        if title is not APIHelper.SKIP:
            self.title = title
        if first is not APIHelper.SKIP:
            self.first = first
        if middle is not APIHelper.SKIP:
            self.middle = middle
        if last is not APIHelper.SKIP:
            self.last = last
        if ssn is not APIHelper.SKIP:
            self.ssn = ssn
        if citizenship is not APIHelper.SKIP:
            self.citizenship = citizenship
        if dob is not APIHelper.SKIP:
            self.dob = dob
        if gender is not APIHelper.SKIP:
            self.gender = gender
        if dl is not APIHelper.SKIP:
            self.dl = dl
        if dlstate is not APIHelper.SKIP:
            self.dlstate = dlstate
        if ownership is not APIHelper.SKIP:
            self.ownership = ownership
        if email is not APIHelper.SKIP:
            self.email = email
        if fax is not APIHelper.SKIP:
            self.fax = fax
        if phone is not APIHelper.SKIP:
            self.phone = phone
        if country is not APIHelper.SKIP:
            self.country = country
        if timezone is not APIHelper.SKIP:
            self.timezone = timezone
        if zip is not APIHelper.SKIP:
            self.zip = zip
        if state is not APIHelper.SKIP:
            self.state = state
        if city is not APIHelper.SKIP:
            self.city = city
        if address_2 is not APIHelper.SKIP:
            self.address_2 = address_2
        if address_1 is not APIHelper.SKIP:
            self.address_1 = address_1
        self.primary = primary
        if credit_score is not APIHelper.SKIP:
            self.credit_score = credit_score
        if credit_score_date is not APIHelper.SKIP:
            self.credit_score_date = credit_score_date
        if significant_responsibility is not APIHelper.SKIP:
            self.significant_responsibility = significant_responsibility
        if politically_exposed is not APIHelper.SKIP:
            self.politically_exposed = politically_exposed
        if mailing_address_1 is not APIHelper.SKIP:
            self.mailing_address_1 = mailing_address_1
        if treasury_prime_roles is not APIHelper.SKIP:
            self.treasury_prime_roles = treasury_prime_roles
        if mailing_address_2 is not APIHelper.SKIP:
            self.mailing_address_2 = mailing_address_2
        if mailing_city is not APIHelper.SKIP:
            self.mailing_city = mailing_city
        if mailing_state is not APIHelper.SKIP:
            self.mailing_state = mailing_state
        if mailing_postal_code is not APIHelper.SKIP:
            self.mailing_postal_code = mailing_postal_code
        if mailing_country is not APIHelper.SKIP:
            self.mailing_country = mailing_country
        if facilitator is not APIHelper.SKIP:
            self.facilitator = facilitator
        if vendor is not APIHelper.SKIP:
            self.vendor = vendor
        if shareable_url is not APIHelper.SKIP:
            self.shareable_url = shareable_url
        if status is not APIHelper.SKIP:
            self.status = status
        if created_at is not APIHelper.SKIP:
            self.created_at = created_at
        if completed_at is not APIHelper.SKIP:
            self.completed_at = completed_at
        if plaid_idv_id is not APIHelper.SKIP:
            self.plaid_idv_id = plaid_idv_id
        if template_id is not APIHelper.SKIP:
            self.template_id = template_id
        self.inactive = inactive
        self.frozen = frozen

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        from payrix.utilities.union_type_lookup import (
            UnionTypeLookUp,
        )

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        created =\
            dictionary.get("created")\
            if dictionary.get("created") else APIHelper.SKIP
        modified =\
            dictionary.get("modified")\
            if dictionary.get("modified") else APIHelper.SKIP
        creator = APIHelper.deserialize_union_type(UnionTypeLookUp.get("MembersResponseCreator"), dictionary.get("creator"), False) if dictionary.get("creator") is not None else APIHelper.SKIP
        modifier =\
            dictionary.get("modifier")\
            if dictionary.get("modifier") else APIHelper.SKIP
        merchant =\
            dictionary.get("merchant")\
            if dictionary.get("merchant") else APIHelper.SKIP
        title =\
            dictionary.get("title")\
            if dictionary.get("title") else APIHelper.SKIP
        first =\
            dictionary.get("first")\
            if dictionary.get("first") else APIHelper.SKIP
        middle =\
            dictionary.get("middle")\
            if dictionary.get("middle") else APIHelper.SKIP
        last =\
            dictionary.get("last")\
            if dictionary.get("last") else APIHelper.SKIP
        ssn = dictionary.get("ssn") if dictionary.get("ssn") else APIHelper.SKIP
        citizenship =\
            dictionary.get("citizenship")\
            if dictionary.get("citizenship") else APIHelper.SKIP
        dob = dictionary.get("dob") if dictionary.get("dob") else APIHelper.SKIP
        gender =\
            dictionary.get("gender")\
            if dictionary.get("gender") else APIHelper.SKIP
        dl = dictionary.get("dl") if dictionary.get("dl") else APIHelper.SKIP
        dlstate =\
            dictionary.get("dlstate")\
            if dictionary.get("dlstate") else APIHelper.SKIP
        ownership =\
            dictionary.get("ownership")\
            if dictionary.get("ownership") else APIHelper.SKIP
        email =\
            dictionary.get("email")\
            if dictionary.get("email") else APIHelper.SKIP
        fax = dictionary.get("fax") if dictionary.get("fax") else APIHelper.SKIP
        phone =\
            dictionary.get("phone")\
            if dictionary.get("phone") else APIHelper.SKIP
        country =\
            dictionary.get("country")\
            if dictionary.get("country") else APIHelper.SKIP
        timezone =\
            dictionary.get("timezone")\
            if dictionary.get("timezone") else APIHelper.SKIP
        zip = dictionary.get("zip") if dictionary.get("zip") else APIHelper.SKIP
        state =\
            dictionary.get("state")\
            if dictionary.get("state") else APIHelper.SKIP
        city =\
            dictionary.get("city")\
            if dictionary.get("city") else APIHelper.SKIP
        address_2 =\
            dictionary.get("address2")\
            if dictionary.get("address2") else APIHelper.SKIP
        address_1 =\
            dictionary.get("address1")\
            if dictionary.get("address1") else APIHelper.SKIP
        primary = dictionary.get("primary") if dictionary.get("primary") else 0
        credit_score =\
            dictionary.get("creditScore")\
            if dictionary.get("creditScore") else APIHelper.SKIP
        credit_score_date =\
            dictionary.get("creditScoreDate")\
            if dictionary.get("creditScoreDate") else APIHelper.SKIP
        significant_responsibility =\
            dictionary.get("significantResponsibility")\
            if dictionary.get("significantResponsibility") else APIHelper.SKIP
        politically_exposed =\
            dictionary.get("politicallyExposed")\
            if dictionary.get("politicallyExposed") else APIHelper.SKIP
        mailing_address_1 =\
            dictionary.get("mailingAddress1")\
            if dictionary.get("mailingAddress1") else APIHelper.SKIP
        treasury_prime_roles =\
            dictionary.get("treasuryPrimeRoles")\
            if dictionary.get("treasuryPrimeRoles") else APIHelper.SKIP
        mailing_address_2 =\
            dictionary.get("mailingAddress2")\
            if dictionary.get("mailingAddress2") else APIHelper.SKIP
        mailing_city =\
            dictionary.get("mailingCity")\
            if dictionary.get("mailingCity") else APIHelper.SKIP
        mailing_state =\
            dictionary.get("mailingState")\
            if dictionary.get("mailingState") else APIHelper.SKIP
        mailing_postal_code =\
            dictionary.get("mailingPostalCode")\
            if dictionary.get("mailingPostalCode") else APIHelper.SKIP
        mailing_country =\
            dictionary.get("mailingCountry")\
            if dictionary.get("mailingCountry") else APIHelper.SKIP
        facilitator =\
            dictionary.get("facilitator")\
            if dictionary.get("facilitator") else APIHelper.SKIP
        vendor =\
            dictionary.get("vendor")\
            if dictionary.get("vendor") else APIHelper.SKIP
        shareable_url =\
            dictionary.get("shareableUrl")\
            if dictionary.get("shareableUrl") else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status") else APIHelper.SKIP
        created_at =\
            dictionary.get("createdAt")\
            if dictionary.get("createdAt") else APIHelper.SKIP
        completed_at =\
            dictionary.get("completedAt")\
            if dictionary.get("completedAt") else APIHelper.SKIP
        plaid_idv_id =\
            dictionary.get("plaidIdvId")\
            if dictionary.get("plaidIdvId") else APIHelper.SKIP
        template_id =\
            dictionary.get("templateId")\
            if dictionary.get("templateId") else APIHelper.SKIP
        inactive = dictionary.get("inactive") if dictionary.get("inactive") else 0
        frozen = dictionary.get("frozen") if dictionary.get("frozen") else 0
        # Return an object of this model
        return cls(id,
                   created,
                   modified,
                   creator,
                   modifier,
                   merchant,
                   title,
                   first,
                   middle,
                   last,
                   ssn,
                   citizenship,
                   dob,
                   gender,
                   dl,
                   dlstate,
                   ownership,
                   email,
                   fax,
                   phone,
                   country,
                   timezone,
                   zip,
                   state,
                   city,
                   address_2,
                   address_1,
                   primary,
                   credit_score,
                   credit_score_date,
                   significant_responsibility,
                   politically_exposed,
                   mailing_address_1,
                   treasury_prime_roles,
                   mailing_address_2,
                   mailing_city,
                   mailing_state,
                   mailing_postal_code,
                   mailing_country,
                   facilitator,
                   vendor,
                   shareable_url,
                   status,
                   created_at,
                   completed_at,
                   plaid_idv_id,
                   template_id,
                   inactive,
                   frozen)

    @classmethod
    def validate(cls, dictionary):
        """Validate dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """
        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"id={(self.id if hasattr(self, 'id') else None)!r}, "
                f"created={(self.created
                     if hasattr(self, 'created') else None)!r}, "
                f"modified={(self.modified
                     if hasattr(self, 'modified') else None)!r}, "
                f"creator={(self.creator
                     if hasattr(self, 'creator') else None)!r}, "
                f"modifier={(self.modifier
                     if hasattr(self, 'modifier') else None)!r}, "
                f"merchant={(self.merchant
                     if hasattr(self, 'merchant') else None)!r}, "
                f"title={(self.title if hasattr(self, 'title') else None)!r}, "
                f"first={(self.first if hasattr(self, 'first') else None)!r}, "
                f"middle={(self.middle if hasattr(self, 'middle') else None)!r}, "
                f"last={(self.last if hasattr(self, 'last') else None)!r}, "
                f"ssn={(self.ssn if hasattr(self, 'ssn') else None)!r}, "
                f"citizenship={(self.citizenship
                     if hasattr(self, 'citizenship') else None)!r}, "
                f"dob={(self.dob if hasattr(self, 'dob') else None)!r}, "
                f"gender={(self.gender if hasattr(self, 'gender') else None)!r}, "
                f"dl={(self.dl if hasattr(self, 'dl') else None)!r}, "
                f"dlstate={(self.dlstate
                     if hasattr(self, 'dlstate') else None)!r}, "
                f"ownership={(self.ownership
                     if hasattr(self, 'ownership') else None)!r}, "
                f"email={(self.email if hasattr(self, 'email') else None)!r}, "
                f"fax={(self.fax if hasattr(self, 'fax') else None)!r}, "
                f"phone={(self.phone if hasattr(self, 'phone') else None)!r}, "
                f"country={(self.country
                     if hasattr(self, 'country') else None)!r}, "
                f"timezone={(self.timezone
                     if hasattr(self, 'timezone') else None)!r}, "
                f"zip={(self.zip if hasattr(self, 'zip') else None)!r}, "
                f"state={(self.state if hasattr(self, 'state') else None)!r}, "
                f"city={(self.city if hasattr(self, 'city') else None)!r}, "
                f"address_2={(self.address_2
                     if hasattr(self, 'address_2') else None)!r}, "
                f"address_1={(self.address_1
                     if hasattr(self, 'address_1') else None)!r}, "
                f"primary={(self.primary
                     if hasattr(self, 'primary') else None)!r}, "
                f"credit_score={(self.credit_score
                     if hasattr(self, 'credit_score') else None)!r}, "
                f"credit_score_date={(self.credit_score_date
                     if hasattr(self, 'credit_score_date') else None)!r}, "
                f"significant_responsibility={(self.significant_responsibility
                     if hasattr(self, 'significant_responsibility') else None)!r}, "
                f"politically_exposed={(self.politically_exposed
                     if hasattr(self, 'politically_exposed') else None)!r}, "
                f"mailing_address_1={(self.mailing_address_1
                     if hasattr(self, 'mailing_address_1') else None)!r}, "
                f"treasury_prime_roles={(self.treasury_prime_roles
                     if hasattr(self, 'treasury_prime_roles') else None)!r}, "
                f"mailing_address_2={(self.mailing_address_2
                     if hasattr(self, 'mailing_address_2') else None)!r}, "
                f"mailing_city={(self.mailing_city
                     if hasattr(self, 'mailing_city') else None)!r}, "
                f"mailing_state={(self.mailing_state
                     if hasattr(self, 'mailing_state') else None)!r}, "
                f"mailing_postal_code={(self.mailing_postal_code
                     if hasattr(self, 'mailing_postal_code') else None)!r}, "
                f"mailing_country={(self.mailing_country
                     if hasattr(self, 'mailing_country') else None)!r}, "
                f"facilitator={(self.facilitator
                     if hasattr(self, 'facilitator') else None)!r}, "
                f"vendor={(self.vendor if hasattr(self, 'vendor') else None)!r}, "
                f"shareable_url={(self.shareable_url
                     if hasattr(self, 'shareable_url') else None)!r}, "
                f"status={(self.status if hasattr(self, 'status') else None)!r}, "
                f"created_at={(self.created_at
                     if hasattr(self, 'created_at') else None)!r}, "
                f"completed_at={(self.completed_at
                     if hasattr(self, 'completed_at') else None)!r}, "
                f"plaid_idv_id={(self.plaid_idv_id
                     if hasattr(self, 'plaid_idv_id') else None)!r}, "
                f"template_id={(self.template_id
                     if hasattr(self, 'template_id') else None)!r}, "
                f"inactive={(self.inactive
                     if hasattr(self, 'inactive') else None)!r}, "
                f"frozen={(self.frozen if hasattr(self, 'frozen') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"id={(self.id if hasattr(self, 'id') else None)!s}, "
                f"created={(self.created
                     if hasattr(self, 'created') else None)!s}, "
                f"modified={(self.modified
                     if hasattr(self, 'modified') else None)!s}, "
                f"creator={(self.creator
                     if hasattr(self, 'creator') else None)!s}, "
                f"modifier={(self.modifier
                     if hasattr(self, 'modifier') else None)!s}, "
                f"merchant={(self.merchant
                     if hasattr(self, 'merchant') else None)!s}, "
                f"title={(self.title if hasattr(self, 'title') else None)!s}, "
                f"first={(self.first if hasattr(self, 'first') else None)!s}, "
                f"middle={(self.middle if hasattr(self, 'middle') else None)!s}, "
                f"last={(self.last if hasattr(self, 'last') else None)!s}, "
                f"ssn={(self.ssn if hasattr(self, 'ssn') else None)!s}, "
                f"citizenship={(self.citizenship
                     if hasattr(self, 'citizenship') else None)!s}, "
                f"dob={(self.dob if hasattr(self, 'dob') else None)!s}, "
                f"gender={(self.gender if hasattr(self, 'gender') else None)!s}, "
                f"dl={(self.dl if hasattr(self, 'dl') else None)!s}, "
                f"dlstate={(self.dlstate
                     if hasattr(self, 'dlstate') else None)!s}, "
                f"ownership={(self.ownership
                     if hasattr(self, 'ownership') else None)!s}, "
                f"email={(self.email if hasattr(self, 'email') else None)!s}, "
                f"fax={(self.fax if hasattr(self, 'fax') else None)!s}, "
                f"phone={(self.phone if hasattr(self, 'phone') else None)!s}, "
                f"country={(self.country
                     if hasattr(self, 'country') else None)!s}, "
                f"timezone={(self.timezone
                     if hasattr(self, 'timezone') else None)!s}, "
                f"zip={(self.zip if hasattr(self, 'zip') else None)!s}, "
                f"state={(self.state if hasattr(self, 'state') else None)!s}, "
                f"city={(self.city if hasattr(self, 'city') else None)!s}, "
                f"address_2={(self.address_2
                     if hasattr(self, 'address_2') else None)!s}, "
                f"address_1={(self.address_1
                     if hasattr(self, 'address_1') else None)!s}, "
                f"primary={(self.primary
                     if hasattr(self, 'primary') else None)!s}, "
                f"credit_score={(self.credit_score
                     if hasattr(self, 'credit_score') else None)!s}, "
                f"credit_score_date={(self.credit_score_date
                     if hasattr(self, 'credit_score_date') else None)!s}, "
                f"significant_responsibility={(self.significant_responsibility
                     if hasattr(self, 'significant_responsibility') else None)!s}, "
                f"politically_exposed={(self.politically_exposed
                     if hasattr(self, 'politically_exposed') else None)!s}, "
                f"mailing_address_1={(self.mailing_address_1
                     if hasattr(self, 'mailing_address_1') else None)!s}, "
                f"treasury_prime_roles={(self.treasury_prime_roles
                     if hasattr(self, 'treasury_prime_roles') else None)!s}, "
                f"mailing_address_2={(self.mailing_address_2
                     if hasattr(self, 'mailing_address_2') else None)!s}, "
                f"mailing_city={(self.mailing_city
                     if hasattr(self, 'mailing_city') else None)!s}, "
                f"mailing_state={(self.mailing_state
                     if hasattr(self, 'mailing_state') else None)!s}, "
                f"mailing_postal_code={(self.mailing_postal_code
                     if hasattr(self, 'mailing_postal_code') else None)!s}, "
                f"mailing_country={(self.mailing_country
                     if hasattr(self, 'mailing_country') else None)!s}, "
                f"facilitator={(self.facilitator
                     if hasattr(self, 'facilitator') else None)!s}, "
                f"vendor={(self.vendor if hasattr(self, 'vendor') else None)!s}, "
                f"shareable_url={(self.shareable_url
                     if hasattr(self, 'shareable_url') else None)!s}, "
                f"status={(self.status if hasattr(self, 'status') else None)!s}, "
                f"created_at={(self.created_at
                     if hasattr(self, 'created_at') else None)!s}, "
                f"completed_at={(self.completed_at
                     if hasattr(self, 'completed_at') else None)!s}, "
                f"plaid_idv_id={(self.plaid_idv_id
                     if hasattr(self, 'plaid_idv_id') else None)!s}, "
                f"template_id={(self.template_id
                     if hasattr(self, 'template_id') else None)!s}, "
                f"inactive={(self.inactive
                     if hasattr(self, 'inactive') else None)!s}, "
                f"frozen={(self.frozen if hasattr(self, 'frozen') else None)!s})")
