# -*- coding: utf-8 -*-

"""
payrix

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from payrix.api_helper import APIHelper
from payrix.models.terminal_txns_payment import TerminalTxnsPayment


class TerminalTxnsPutRequest(object):

    """Implementation of the 'terminalTxnsPutRequest' model.

    Attributes:
        bin_type (BinTypeEnum): The type of bank issuer number (BIN) that
            allows for resulting transactions.  <details> <summary>Valid
            Values</summary>  - `CREDIT` - **Credit BIN Type.** - `DEBIT` -
            **Debit BIN Type.** - `PREPAID` - **Prepaid BIN Type.**  </details>
        expiration (str): The expiration date of this Transaction. This field
            is stored as a text string in 'MMYY' format, where 'MM' is the
            number of a month and 'YY' is the last two digits of a year. For
            example, '0623' for June 2023. The value must reflect a future
            date.
        payment (TerminalTxnsPayment): The payment method associated with this
            Transaction, including the card details.
        trace_number (int): Sequencial number that uniquely identifies the
            terminalTxn.
        txn (str): The related txn this terminalTxn belongs to.
        token (str): The ID of the token record to associate with this
            terminal transaction request.
        payment_number (int): The last four numbers of the credit card
            associated with this Transaction.
        payment_method (TerminalTxnPaymentMethodEnum): The payment method for
            this Transaction.
        tip (int): This field indicates the tip amount associated with a
            transaction. This value is for reporting purposes only, because
            transaction amount includes this amount in the total.
        originating_app (str): Field identifying Payrix PAX terminal
            originating app.
        oemt_txn_ref_number (str): Field identifying original Payrix Verifone
            transaction reference number, used for refunds and cancellation
            request.
        pos_application_id (str): Express assigned identifier i.e. Software Id
            being used in express terminal.
        unattended (UnattendedEnum): Whether the card was swiped at an
            unattended terminal during this Transaction. This field is set to
            '0' by default. <details> <summary>Valid Values</summary>  - `0` -
            **Attended terminal.** - `1` - **Unattended terminal.**  </details>
        pos_application_name (str): Software Name being used in express
            terminal.
        pos_application_version (str): Software version being used in express
            terminal.
        customer_reference_number (str): Express Reference Number.
        gateway_transaction_id (str): The gateway transaction ID relates to
            Express Transaction ID.
        customer_ticket_number (str): Express ticket Number.
        client_ip (str): The client IP address from which the transaction was
            created, valid values are any IPv4 or IPv6 address.
        description (str): A description of this Transaction. This field is
            stored as a text string and must be between 0 and 1000 characters
            long.
        swiped (SwipedEnum): Whether the card was swiped during this
            Transaction. This field is set to '1' automatically if 'track'
            data was received.   <details> <summary>Valid Values</summary>  -
            `0` - **Not Swiped.** - `1` - **Swiped.**  </details>
        emv (EmvEnum): Whether the card was dipped (using the EMV chip) during
            this Transaction.  <details> <summary>Valid Values</summary>  -
            `0` - **Not dipped.** - `1` - **Dipped.**  </details>
        entry_mode (EntryModeEnum): How payment information has been entered,
            including manually keyed entries, card swipes with track 1 or 2
            data received, card dips with EMV chip data received, contactless
            card reads with track or EMV data received, and ApplePay read with
            cryptogram data received.  <details> <summary>Valid
            Values</summary>  - `1` - **Manually keyed entry.** - `2` - **Card
            swiped. Track 1 received.** - `3` - **Card swiped. Track 2
            received.** - `4` - **Card swiped. Track 1 & 2 received.** - `5` -
            **Card dipped. EMV chip received.** - `6` - **Contactless card
            read. Track or EMV data received.** - `7` - **Track Data from Card
            Swipe after EMV chip failure.** - `8` - **Track Data from Manually
            keyed entry after EMV chip failure.** - `9` - **ApplePay** - `10`
            - **Google Pay.** - `11` - **Merchant created transaction.** -
            `12` - **Invoice payment.** - `13` - **Merchant created
            transaction in payrix portal.** - `14` - **Invoice payment from
            payrix portal.**  </details>
        first (str): The first name associated with this Transaction. For
            eCheck transactions, either first or last is required.
        last (str): The last name associated with this Transaction. For eCheck
            transactions, either first or last is required.
        middle (str): The middle name associated with this Transaction.
        order (str): The identifier of the Order associated with this
            Transaction, This field is stored as a text string and must be
            between 0 and 1000 characters long.
        reserved (Reserved1Enum): Indicates whether the Transaction is
            reserved and the action that will be taken as a result.  <details>
            <summary>Valid Values</summary>  - `0` - **No reserve.** 
            </details>
        signature (SignatureEnum): Whether a signature should be captured
            during this Transaction.  * You can set this field if you want the
            terminal to take a signature for the Transaction. * The API also
            sets this field automatically if you associate a signature to the
            Transaction by creating a 'terminalTxnDatas' resource.  <details>
            <summary>Valid Values</summary>  - `0` - **Not captured.** - `1` -
            **Captured.**  </details>
        total (int): The total amount of this Transaction, This field is
            specified as an integer in cents.
        status (TerminalTxnStatusEnum): The status of the Transaction. 
            <details> <summary>Valid Values</summary>  - `0` - **Pending.** -
            `1` - **Approved.** Payments can be voided or cancelled. - `2` -
            **Failed.** - `3` - **Captured.** Payments can be refunded. - `4`
            - **Settled.** Payments can be refunded. - `5` - **Returned.**
            Payments have been successfully refunded.  </details>
        card_network_transaction_id (str): Card network transaction ID
            associated with this transaction.
        omnitoken (str): The OmniToken associated with this Transaction.
        convenience_fee (int): The amount of the total sum of this Transaction
            that is made up of convenience fee. Fee charged when card payment
            is an alternative form of payment not ordinarily accepted by a
            merchant or service provider. This field is specified as an
            integer in cents. [currently not active]
        surcharge (int): Surcharge amount included in the total amount of the
            transaction. A surcharge fee is an additional charge added to the
            price of a purchase when a customer pays with a credit card. This
            field is specified as an integer in cents.
        soft_pos_device_type_indicator (str): The device type indicator for
            the terminal.  <details> <summary>Valid Values</summary>    - `1`
            - **Apple (Worldpay as PSP)**   - `2` - **Android (Worldpay as
            PSP)**   - `3` - **Apple (Worldpay not PSP)**   - `4` - **Android
            (Worldpay not PSP)**    </details>
        soft_pos_id (str): The software POS ID.
        hsa_fsa_card_indicator (HsaFsaCardIndicatorEnum): Indicates if the
            card is a Flexible Spending Account (FSA) or Health Savings
            Account (HSA) card. <details> <summary>Valid Values</summary>  -
            `0` - **Not an HSA/FSA card.** - `1` - **HSA/FSA card.** 
            </details>
        gateway_terminal_id (str): The gateway terminal ID.
        descriptor (str): The billing Descriptor that is used when the
            transaction is part of a subscription.
        card_network_bank_net_reference_number (str): The reference number
            associated with the card network.
        card_network_bank_net_settlement_date (str): The settlement date
            associated with the card network.
        inactive (InactiveEnum): Whether this resource is marked as inactive. 
            <details> <summary>Valid Values</summary>  - `0` - **Active** -
            `1` - **Inactive**  </details>
        frozen (FrozenEnum): Whether this resource is marked as frozen. 
            <details> <summary>Valid Values</summary>  - `0` - **Not Frozen**
            - `1` - **Frozen**  </details>

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "bin_type": 'binType',
        "expiration": 'expiration',
        "payment": 'payment',
        "trace_number": 'traceNumber',
        "txn": 'txn',
        "token": 'token',
        "payment_number": 'paymentNumber',
        "payment_method": 'paymentMethod',
        "tip": 'tip',
        "originating_app": 'originatingApp',
        "oemt_txn_ref_number": 'OEMTTxnRefNumber',
        "pos_application_id": 'posApplicationId',
        "unattended": 'unattended',
        "pos_application_name": 'posApplicationName',
        "pos_application_version": 'posApplicationVersion',
        "customer_reference_number": 'customerReferenceNumber',
        "gateway_transaction_id": 'gatewayTransactionId',
        "customer_ticket_number": 'customerTicketNumber',
        "client_ip": 'clientIp',
        "description": 'description',
        "swiped": 'swiped',
        "emv": 'emv',
        "entry_mode": 'entryMode',
        "first": 'first',
        "last": 'last',
        "middle": 'middle',
        "order": 'order',
        "reserved": 'reserved',
        "signature": 'signature',
        "total": 'total',
        "status": 'status',
        "card_network_transaction_id": 'cardNetworkTransactionId',
        "omnitoken": 'omnitoken',
        "convenience_fee": 'convenienceFee',
        "surcharge": 'surcharge',
        "soft_pos_device_type_indicator": 'softPosDeviceTypeIndicator',
        "soft_pos_id": 'softPosId',
        "hsa_fsa_card_indicator": 'hsaFsaCardIndicator',
        "gateway_terminal_id": 'gatewayTerminalId',
        "descriptor": 'descriptor',
        "card_network_bank_net_reference_number": 'cardNetworkBankNetReferenceNumber',
        "card_network_bank_net_settlement_date": 'cardNetworkBankNetSettlementDate',
        "inactive": 'inactive',
        "frozen": 'frozen'
    }

    _optionals = [
        'bin_type',
        'expiration',
        'payment',
        'trace_number',
        'txn',
        'token',
        'payment_number',
        'payment_method',
        'tip',
        'originating_app',
        'oemt_txn_ref_number',
        'pos_application_id',
        'unattended',
        'pos_application_name',
        'pos_application_version',
        'customer_reference_number',
        'gateway_transaction_id',
        'customer_ticket_number',
        'client_ip',
        'description',
        'swiped',
        'emv',
        'entry_mode',
        'first',
        'last',
        'middle',
        'order',
        'reserved',
        'signature',
        'total',
        'status',
        'card_network_transaction_id',
        'omnitoken',
        'convenience_fee',
        'surcharge',
        'soft_pos_device_type_indicator',
        'soft_pos_id',
        'hsa_fsa_card_indicator',
        'gateway_terminal_id',
        'descriptor',
        'card_network_bank_net_reference_number',
        'card_network_bank_net_settlement_date',
        'inactive',
        'frozen',
    ]

    def __init__(self,
                 bin_type=APIHelper.SKIP,
                 expiration=APIHelper.SKIP,
                 payment=APIHelper.SKIP,
                 trace_number=APIHelper.SKIP,
                 txn=APIHelper.SKIP,
                 token=APIHelper.SKIP,
                 payment_number=APIHelper.SKIP,
                 payment_method=APIHelper.SKIP,
                 tip=APIHelper.SKIP,
                 originating_app=APIHelper.SKIP,
                 oemt_txn_ref_number=APIHelper.SKIP,
                 pos_application_id=APIHelper.SKIP,
                 unattended=APIHelper.SKIP,
                 pos_application_name=APIHelper.SKIP,
                 pos_application_version=APIHelper.SKIP,
                 customer_reference_number=APIHelper.SKIP,
                 gateway_transaction_id=APIHelper.SKIP,
                 customer_ticket_number=APIHelper.SKIP,
                 client_ip=APIHelper.SKIP,
                 description=APIHelper.SKIP,
                 swiped=APIHelper.SKIP,
                 emv=APIHelper.SKIP,
                 entry_mode=APIHelper.SKIP,
                 first=APIHelper.SKIP,
                 last=APIHelper.SKIP,
                 middle=APIHelper.SKIP,
                 order=APIHelper.SKIP,
                 reserved=APIHelper.SKIP,
                 signature=APIHelper.SKIP,
                 total=APIHelper.SKIP,
                 status=0,
                 card_network_transaction_id=APIHelper.SKIP,
                 omnitoken=APIHelper.SKIP,
                 convenience_fee=APIHelper.SKIP,
                 surcharge=APIHelper.SKIP,
                 soft_pos_device_type_indicator=APIHelper.SKIP,
                 soft_pos_id=APIHelper.SKIP,
                 hsa_fsa_card_indicator=APIHelper.SKIP,
                 gateway_terminal_id=APIHelper.SKIP,
                 descriptor=APIHelper.SKIP,
                 card_network_bank_net_reference_number=APIHelper.SKIP,
                 card_network_bank_net_settlement_date=APIHelper.SKIP,
                 inactive=0,
                 frozen=0):
        """Constructor for the TerminalTxnsPutRequest class"""

        # Initialize members of the class
        if bin_type is not APIHelper.SKIP:
            self.bin_type = bin_type 
        if expiration is not APIHelper.SKIP:
            self.expiration = expiration 
        if payment is not APIHelper.SKIP:
            self.payment = payment 
        if trace_number is not APIHelper.SKIP:
            self.trace_number = trace_number 
        if txn is not APIHelper.SKIP:
            self.txn = txn 
        if token is not APIHelper.SKIP:
            self.token = token 
        if payment_number is not APIHelper.SKIP:
            self.payment_number = payment_number 
        if payment_method is not APIHelper.SKIP:
            self.payment_method = payment_method 
        if tip is not APIHelper.SKIP:
            self.tip = tip 
        if originating_app is not APIHelper.SKIP:
            self.originating_app = originating_app 
        if oemt_txn_ref_number is not APIHelper.SKIP:
            self.oemt_txn_ref_number = oemt_txn_ref_number 
        if pos_application_id is not APIHelper.SKIP:
            self.pos_application_id = pos_application_id 
        if unattended is not APIHelper.SKIP:
            self.unattended = unattended 
        if pos_application_name is not APIHelper.SKIP:
            self.pos_application_name = pos_application_name 
        if pos_application_version is not APIHelper.SKIP:
            self.pos_application_version = pos_application_version 
        if customer_reference_number is not APIHelper.SKIP:
            self.customer_reference_number = customer_reference_number 
        if gateway_transaction_id is not APIHelper.SKIP:
            self.gateway_transaction_id = gateway_transaction_id 
        if customer_ticket_number is not APIHelper.SKIP:
            self.customer_ticket_number = customer_ticket_number 
        if client_ip is not APIHelper.SKIP:
            self.client_ip = client_ip 
        if description is not APIHelper.SKIP:
            self.description = description 
        if swiped is not APIHelper.SKIP:
            self.swiped = swiped 
        if emv is not APIHelper.SKIP:
            self.emv = emv 
        if entry_mode is not APIHelper.SKIP:
            self.entry_mode = entry_mode 
        if first is not APIHelper.SKIP:
            self.first = first 
        if last is not APIHelper.SKIP:
            self.last = last 
        if middle is not APIHelper.SKIP:
            self.middle = middle 
        if order is not APIHelper.SKIP:
            self.order = order 
        if reserved is not APIHelper.SKIP:
            self.reserved = reserved 
        if signature is not APIHelper.SKIP:
            self.signature = signature 
        if total is not APIHelper.SKIP:
            self.total = total 
        self.status = status 
        if card_network_transaction_id is not APIHelper.SKIP:
            self.card_network_transaction_id = card_network_transaction_id 
        if omnitoken is not APIHelper.SKIP:
            self.omnitoken = omnitoken 
        if convenience_fee is not APIHelper.SKIP:
            self.convenience_fee = convenience_fee 
        if surcharge is not APIHelper.SKIP:
            self.surcharge = surcharge 
        if soft_pos_device_type_indicator is not APIHelper.SKIP:
            self.soft_pos_device_type_indicator = soft_pos_device_type_indicator 
        if soft_pos_id is not APIHelper.SKIP:
            self.soft_pos_id = soft_pos_id 
        if hsa_fsa_card_indicator is not APIHelper.SKIP:
            self.hsa_fsa_card_indicator = hsa_fsa_card_indicator 
        if gateway_terminal_id is not APIHelper.SKIP:
            self.gateway_terminal_id = gateway_terminal_id 
        if descriptor is not APIHelper.SKIP:
            self.descriptor = descriptor 
        if card_network_bank_net_reference_number is not APIHelper.SKIP:
            self.card_network_bank_net_reference_number = card_network_bank_net_reference_number 
        if card_network_bank_net_settlement_date is not APIHelper.SKIP:
            self.card_network_bank_net_settlement_date = card_network_bank_net_settlement_date 
        self.inactive = inactive 
        self.frozen = frozen 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        bin_type = dictionary.get("binType") if dictionary.get("binType") else APIHelper.SKIP
        expiration = dictionary.get("expiration") if dictionary.get("expiration") else APIHelper.SKIP
        payment = TerminalTxnsPayment.from_dictionary(dictionary.get('payment')) if 'payment' in dictionary.keys() else APIHelper.SKIP
        trace_number = dictionary.get("traceNumber") if dictionary.get("traceNumber") else APIHelper.SKIP
        txn = dictionary.get("txn") if dictionary.get("txn") else APIHelper.SKIP
        token = dictionary.get("token") if dictionary.get("token") else APIHelper.SKIP
        payment_number = dictionary.get("paymentNumber") if dictionary.get("paymentNumber") else APIHelper.SKIP
        payment_method = dictionary.get("paymentMethod") if dictionary.get("paymentMethod") else APIHelper.SKIP
        tip = dictionary.get("tip") if dictionary.get("tip") else APIHelper.SKIP
        originating_app = dictionary.get("originatingApp") if dictionary.get("originatingApp") else APIHelper.SKIP
        oemt_txn_ref_number = dictionary.get("OEMTTxnRefNumber") if dictionary.get("OEMTTxnRefNumber") else APIHelper.SKIP
        pos_application_id = dictionary.get("posApplicationId") if dictionary.get("posApplicationId") else APIHelper.SKIP
        unattended = dictionary.get("unattended") if dictionary.get("unattended") else APIHelper.SKIP
        pos_application_name = dictionary.get("posApplicationName") if dictionary.get("posApplicationName") else APIHelper.SKIP
        pos_application_version = dictionary.get("posApplicationVersion") if dictionary.get("posApplicationVersion") else APIHelper.SKIP
        customer_reference_number = dictionary.get("customerReferenceNumber") if dictionary.get("customerReferenceNumber") else APIHelper.SKIP
        gateway_transaction_id = dictionary.get("gatewayTransactionId") if dictionary.get("gatewayTransactionId") else APIHelper.SKIP
        customer_ticket_number = dictionary.get("customerTicketNumber") if dictionary.get("customerTicketNumber") else APIHelper.SKIP
        client_ip = dictionary.get("clientIp") if dictionary.get("clientIp") else APIHelper.SKIP
        description = dictionary.get("description") if dictionary.get("description") else APIHelper.SKIP
        swiped = dictionary.get("swiped") if dictionary.get("swiped") else APIHelper.SKIP
        emv = dictionary.get("emv") if dictionary.get("emv") else APIHelper.SKIP
        entry_mode = dictionary.get("entryMode") if dictionary.get("entryMode") else APIHelper.SKIP
        first = dictionary.get("first") if dictionary.get("first") else APIHelper.SKIP
        last = dictionary.get("last") if dictionary.get("last") else APIHelper.SKIP
        middle = dictionary.get("middle") if dictionary.get("middle") else APIHelper.SKIP
        order = dictionary.get("order") if dictionary.get("order") else APIHelper.SKIP
        reserved = dictionary.get("reserved") if dictionary.get("reserved") else APIHelper.SKIP
        signature = dictionary.get("signature") if dictionary.get("signature") else APIHelper.SKIP
        total = dictionary.get("total") if dictionary.get("total") else APIHelper.SKIP
        status = dictionary.get("status") if dictionary.get("status") else 0
        card_network_transaction_id = dictionary.get("cardNetworkTransactionId") if dictionary.get("cardNetworkTransactionId") else APIHelper.SKIP
        omnitoken = dictionary.get("omnitoken") if dictionary.get("omnitoken") else APIHelper.SKIP
        convenience_fee = dictionary.get("convenienceFee") if dictionary.get("convenienceFee") else APIHelper.SKIP
        surcharge = dictionary.get("surcharge") if dictionary.get("surcharge") else APIHelper.SKIP
        soft_pos_device_type_indicator = dictionary.get("softPosDeviceTypeIndicator") if dictionary.get("softPosDeviceTypeIndicator") else APIHelper.SKIP
        soft_pos_id = dictionary.get("softPosId") if dictionary.get("softPosId") else APIHelper.SKIP
        hsa_fsa_card_indicator = dictionary.get("hsaFsaCardIndicator") if dictionary.get("hsaFsaCardIndicator") else APIHelper.SKIP
        gateway_terminal_id = dictionary.get("gatewayTerminalId") if dictionary.get("gatewayTerminalId") else APIHelper.SKIP
        descriptor = dictionary.get("descriptor") if dictionary.get("descriptor") else APIHelper.SKIP
        card_network_bank_net_reference_number = dictionary.get("cardNetworkBankNetReferenceNumber") if dictionary.get("cardNetworkBankNetReferenceNumber") else APIHelper.SKIP
        card_network_bank_net_settlement_date = dictionary.get("cardNetworkBankNetSettlementDate") if dictionary.get("cardNetworkBankNetSettlementDate") else APIHelper.SKIP
        inactive = dictionary.get("inactive") if dictionary.get("inactive") else 0
        frozen = dictionary.get("frozen") if dictionary.get("frozen") else 0
        # Return an object of this model
        return cls(bin_type,
                   expiration,
                   payment,
                   trace_number,
                   txn,
                   token,
                   payment_number,
                   payment_method,
                   tip,
                   originating_app,
                   oemt_txn_ref_number,
                   pos_application_id,
                   unattended,
                   pos_application_name,
                   pos_application_version,
                   customer_reference_number,
                   gateway_transaction_id,
                   customer_ticket_number,
                   client_ip,
                   description,
                   swiped,
                   emv,
                   entry_mode,
                   first,
                   last,
                   middle,
                   order,
                   reserved,
                   signature,
                   total,
                   status,
                   card_network_transaction_id,
                   omnitoken,
                   convenience_fee,
                   surcharge,
                   soft_pos_device_type_indicator,
                   soft_pos_id,
                   hsa_fsa_card_indicator,
                   gateway_terminal_id,
                   descriptor,
                   card_network_bank_net_reference_number,
                   card_network_bank_net_settlement_date,
                   inactive,
                   frozen)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'bin_type={(self.bin_type if hasattr(self, "bin_type") else None)!r}, '
                f'expiration={(self.expiration if hasattr(self, "expiration") else None)!r}, '
                f'payment={(self.payment if hasattr(self, "payment") else None)!r}, '
                f'trace_number={(self.trace_number if hasattr(self, "trace_number") else None)!r}, '
                f'txn={(self.txn if hasattr(self, "txn") else None)!r}, '
                f'token={(self.token if hasattr(self, "token") else None)!r}, '
                f'payment_number={(self.payment_number if hasattr(self, "payment_number") else None)!r}, '
                f'payment_method={(self.payment_method if hasattr(self, "payment_method") else None)!r}, '
                f'tip={(self.tip if hasattr(self, "tip") else None)!r}, '
                f'originating_app={(self.originating_app if hasattr(self, "originating_app") else None)!r}, '
                f'oemt_txn_ref_number={(self.oemt_txn_ref_number if hasattr(self, "oemt_txn_ref_number") else None)!r}, '
                f'pos_application_id={(self.pos_application_id if hasattr(self, "pos_application_id") else None)!r}, '
                f'unattended={(self.unattended if hasattr(self, "unattended") else None)!r}, '
                f'pos_application_name={(self.pos_application_name if hasattr(self, "pos_application_name") else None)!r}, '
                f'pos_application_version={(self.pos_application_version if hasattr(self, "pos_application_version") else None)!r}, '
                f'customer_reference_number={(self.customer_reference_number if hasattr(self, "customer_reference_number") else None)!r}, '
                f'gateway_transaction_id={(self.gateway_transaction_id if hasattr(self, "gateway_transaction_id") else None)!r}, '
                f'customer_ticket_number={(self.customer_ticket_number if hasattr(self, "customer_ticket_number") else None)!r}, '
                f'client_ip={(self.client_ip if hasattr(self, "client_ip") else None)!r}, '
                f'description={(self.description if hasattr(self, "description") else None)!r}, '
                f'swiped={(self.swiped if hasattr(self, "swiped") else None)!r}, '
                f'emv={(self.emv if hasattr(self, "emv") else None)!r}, '
                f'entry_mode={(self.entry_mode if hasattr(self, "entry_mode") else None)!r}, '
                f'first={(self.first if hasattr(self, "first") else None)!r}, '
                f'last={(self.last if hasattr(self, "last") else None)!r}, '
                f'middle={(self.middle if hasattr(self, "middle") else None)!r}, '
                f'order={(self.order if hasattr(self, "order") else None)!r}, '
                f'reserved={(self.reserved if hasattr(self, "reserved") else None)!r}, '
                f'signature={(self.signature if hasattr(self, "signature") else None)!r}, '
                f'total={(self.total if hasattr(self, "total") else None)!r}, '
                f'status={(self.status if hasattr(self, "status") else None)!r}, '
                f'card_network_transaction_id={(self.card_network_transaction_id if hasattr(self, "card_network_transaction_id") else None)!r}, '
                f'omnitoken={(self.omnitoken if hasattr(self, "omnitoken") else None)!r}, '
                f'convenience_fee={(self.convenience_fee if hasattr(self, "convenience_fee") else None)!r}, '
                f'surcharge={(self.surcharge if hasattr(self, "surcharge") else None)!r}, '
                f'soft_pos_device_type_indicator={(self.soft_pos_device_type_indicator if hasattr(self, "soft_pos_device_type_indicator") else None)!r}, '
                f'soft_pos_id={(self.soft_pos_id if hasattr(self, "soft_pos_id") else None)!r}, '
                f'hsa_fsa_card_indicator={(self.hsa_fsa_card_indicator if hasattr(self, "hsa_fsa_card_indicator") else None)!r}, '
                f'gateway_terminal_id={(self.gateway_terminal_id if hasattr(self, "gateway_terminal_id") else None)!r}, '
                f'descriptor={(self.descriptor if hasattr(self, "descriptor") else None)!r}, '
                f'card_network_bank_net_reference_number={(self.card_network_bank_net_reference_number if hasattr(self, "card_network_bank_net_reference_number") else None)!r}, '
                f'card_network_bank_net_settlement_date={(self.card_network_bank_net_settlement_date if hasattr(self, "card_network_bank_net_settlement_date") else None)!r}, '
                f'inactive={(self.inactive if hasattr(self, "inactive") else None)!r}, '
                f'frozen={(self.frozen if hasattr(self, "frozen") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'bin_type={(self.bin_type if hasattr(self, "bin_type") else None)!s}, '
                f'expiration={(self.expiration if hasattr(self, "expiration") else None)!s}, '
                f'payment={(self.payment if hasattr(self, "payment") else None)!s}, '
                f'trace_number={(self.trace_number if hasattr(self, "trace_number") else None)!s}, '
                f'txn={(self.txn if hasattr(self, "txn") else None)!s}, '
                f'token={(self.token if hasattr(self, "token") else None)!s}, '
                f'payment_number={(self.payment_number if hasattr(self, "payment_number") else None)!s}, '
                f'payment_method={(self.payment_method if hasattr(self, "payment_method") else None)!s}, '
                f'tip={(self.tip if hasattr(self, "tip") else None)!s}, '
                f'originating_app={(self.originating_app if hasattr(self, "originating_app") else None)!s}, '
                f'oemt_txn_ref_number={(self.oemt_txn_ref_number if hasattr(self, "oemt_txn_ref_number") else None)!s}, '
                f'pos_application_id={(self.pos_application_id if hasattr(self, "pos_application_id") else None)!s}, '
                f'unattended={(self.unattended if hasattr(self, "unattended") else None)!s}, '
                f'pos_application_name={(self.pos_application_name if hasattr(self, "pos_application_name") else None)!s}, '
                f'pos_application_version={(self.pos_application_version if hasattr(self, "pos_application_version") else None)!s}, '
                f'customer_reference_number={(self.customer_reference_number if hasattr(self, "customer_reference_number") else None)!s}, '
                f'gateway_transaction_id={(self.gateway_transaction_id if hasattr(self, "gateway_transaction_id") else None)!s}, '
                f'customer_ticket_number={(self.customer_ticket_number if hasattr(self, "customer_ticket_number") else None)!s}, '
                f'client_ip={(self.client_ip if hasattr(self, "client_ip") else None)!s}, '
                f'description={(self.description if hasattr(self, "description") else None)!s}, '
                f'swiped={(self.swiped if hasattr(self, "swiped") else None)!s}, '
                f'emv={(self.emv if hasattr(self, "emv") else None)!s}, '
                f'entry_mode={(self.entry_mode if hasattr(self, "entry_mode") else None)!s}, '
                f'first={(self.first if hasattr(self, "first") else None)!s}, '
                f'last={(self.last if hasattr(self, "last") else None)!s}, '
                f'middle={(self.middle if hasattr(self, "middle") else None)!s}, '
                f'order={(self.order if hasattr(self, "order") else None)!s}, '
                f'reserved={(self.reserved if hasattr(self, "reserved") else None)!s}, '
                f'signature={(self.signature if hasattr(self, "signature") else None)!s}, '
                f'total={(self.total if hasattr(self, "total") else None)!s}, '
                f'status={(self.status if hasattr(self, "status") else None)!s}, '
                f'card_network_transaction_id={(self.card_network_transaction_id if hasattr(self, "card_network_transaction_id") else None)!s}, '
                f'omnitoken={(self.omnitoken if hasattr(self, "omnitoken") else None)!s}, '
                f'convenience_fee={(self.convenience_fee if hasattr(self, "convenience_fee") else None)!s}, '
                f'surcharge={(self.surcharge if hasattr(self, "surcharge") else None)!s}, '
                f'soft_pos_device_type_indicator={(self.soft_pos_device_type_indicator if hasattr(self, "soft_pos_device_type_indicator") else None)!s}, '
                f'soft_pos_id={(self.soft_pos_id if hasattr(self, "soft_pos_id") else None)!s}, '
                f'hsa_fsa_card_indicator={(self.hsa_fsa_card_indicator if hasattr(self, "hsa_fsa_card_indicator") else None)!s}, '
                f'gateway_terminal_id={(self.gateway_terminal_id if hasattr(self, "gateway_terminal_id") else None)!s}, '
                f'descriptor={(self.descriptor if hasattr(self, "descriptor") else None)!s}, '
                f'card_network_bank_net_reference_number={(self.card_network_bank_net_reference_number if hasattr(self, "card_network_bank_net_reference_number") else None)!s}, '
                f'card_network_bank_net_settlement_date={(self.card_network_bank_net_settlement_date if hasattr(self, "card_network_bank_net_settlement_date") else None)!s}, '
                f'inactive={(self.inactive if hasattr(self, "inactive") else None)!s}, '
                f'frozen={(self.frozen if hasattr(self, "frozen") else None)!s})')
