"""verizon.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from verizon.api_helper import APIHelper


class ActiveTriggerIndicator(object):
    """Implementation of the 'ActiveTriggerIndicator' model.

    Whether the trigger is active or not.

    Attributes:
        active (bool): Indicates if the trigger is active<br />True - trigger
            is active<br />False - trigger is not active.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "active": "active",
    }

    _optionals = [
        "active",
    ]

    def __init__(self,
                 active=APIHelper.SKIP):
        """Initialize a ActiveTriggerIndicator instance."""
        # Initialize members of the class
        if active is not APIHelper.SKIP:
            self.active = active

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        active =\
            dictionary.get("active")\
            if "active" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(active)

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"active={(self.active if hasattr(self, 'active') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"active={(self.active if hasattr(self, 'active') else None)!s})")
