# -*- coding: utf-8 -*-

"""
typecombinatorspecial

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from typecombinatorspecial.api_helper import APIHelper
from typecombinatorspecial.models.asia_continent_enum import AsiaContinentEnum


class InnerModel2(object):

    """Implementation of the 'InnerModel2' model.

    This class contains enum types in oneOf/anyOf cases.

    Attributes:
        country (AsiaContinentEnum): The model property of type
            AsiaContinentEnum.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "country": 'country'
    }

    def __init__(self,
                 country=None):
        """Constructor for the InnerModel2 class"""

        # Initialize members of the class
        self.country = country 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        country = dictionary.get("country") if dictionary.get("country") else None
        # Return an object of this model
        return cls(country)

    @classmethod
    def validate(cls, dictionary):
        """Validates dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """

        if isinstance(dictionary, cls):
            return APIHelper.is_valid_type(value=dictionary.country,
                                           type_callable=lambda value: AsiaContinentEnum.validate(value))

        if not isinstance(dictionary, dict):
            return False

        return APIHelper.is_valid_type(value=dictionary.get('country'),
                                       type_callable=lambda value: AsiaContinentEnum.validate(value))

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'country={self.country!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'country={self.country!s})')
