"""enterpriseapimerchantaccountcreated.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

class AcknowledgeResponse(object):
    """Implementation of the 'AcknowledgeResponse' model.

    Attributes:
        http_status_code (str): Http response status Code
        http_status_message (str): Http response status Message

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "http_status_code": "httpStatusCode",
        "http_status_message": "httpStatusMessage",
    }

    def __init__(self,
                 http_status_code=None,
                 http_status_message=None):
        """Initialize a AcknowledgeResponse instance."""
        # Initialize members of the class
        self.http_status_code = http_status_code
        self.http_status_message = http_status_message

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        http_status_code =\
            dictionary.get("httpStatusCode")\
            if dictionary.get("httpStatusCode") else None
        http_status_message =\
            dictionary.get("httpStatusMessage")\
            if dictionary.get("httpStatusMessage") else None
        # Return an object of this model
        return cls(http_status_code,
                   http_status_message)

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"http_status_code={self.http_status_code!r}, "
                f"http_status_message={self.http_status_message!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"http_status_code={self.http_status_code!s}, "
                f"http_status_message={self.http_status_message!s})")
