"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from apimatic_core.authentication.multiple.and_auth_group import (
    And,
)
from apimatic_core.authentication.multiple.single_auth import (
    Single,
)
from apimatic_core.request_builder import RequestBuilder
from apimatic_core.response_handler import ResponseHandler
from apimatic_core.types.parameter import Parameter

from fortisapi.api_helper import APIHelper
from fortisapi.configuration import Server
from fortisapi.controllers.base_controller import (
    BaseController,
)
from fortisapi.exceptions.response_401_token_exception import (
    Response401tokenException,
)
from fortisapi.exceptions.response_412_exception import (
    Response412Exception,
)
from fortisapi.http.http_method_enum import (
    HttpMethodEnum,
)
from fortisapi.models.response_transaction import (
    ResponseTransaction,
)


class TransactionsUpdatesController(BaseController):
    """A Controller to access Endpoints in the fortisapi API."""

    def __init__(self, config):
        """Initialize TransactionsUpdatesController object."""
        super(TransactionsUpdatesController, self).__init__(config)

    def void(self,
             transaction_id,
             expand=None):
        """Perform a PUT request to /v1/transactions/{transaction_id}/void.

        Void a transaction

        Args:
            transaction_id (str): Transaction ID
            expand (List[Expand54Enum], optional): Most endpoints in the API
                have a way to retrieve extra data related to the current
                record being retrieved. For example, if the API request is for
                the accountvaults endpoint, and the end user also needs to
                know which contact the token belongs to, this data can be
                returned in the accountvaults endpoint request.

        Returns:
            ApiResponse: An object with the response value as well as other
                useful information such as status codes and headers. OK

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/transactions/{transaction_id}/void")
            .http_method(HttpMethodEnum.PUT)
            .template_param(Parameter()
                            .key("transaction_id")
                            .value(transaction_id)
                            .should_encode(True))
            .query_param(Parameter()
                         .key("expand")
                         .value(expand))
            .header_param(Parameter()
                          .key("accept")
                          .value("application/json"))
            .auth(And(Single("user-id"), Single("user-api-key"),
                Single("developer-id"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ResponseTransaction.from_dictionary)
            .is_api_response(True)
            .local_error("401", "Unauthorized", Response401tokenException),
        ).execute()

    def void_1(self,
               transaction_id,
               body,
               expand=None):
        """Perform a PATCH request to /v1/transactions/{transaction_id}/void.

        Void a transaction

        Args:
            transaction_id (str): Transaction ID
            body (V1TransactionsVoidRequest): The request body parameter.
            expand (List[Expand54Enum], optional): Most endpoints in the API
                have a way to retrieve extra data related to the current
                record being retrieved. For example, if the API request is for
                the accountvaults endpoint, and the end user also needs to
                know which contact the token belongs to, this data can be
                returned in the accountvaults endpoint request.

        Returns:
            ApiResponse: An object with the response value as well as other
                useful information such as status codes and headers. OK

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/transactions/{transaction_id}/void")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                            .key("transaction_id")
                            .value(transaction_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key("Content-Type")
                          .value("application/json"))
            .body_param(Parameter()
                        .value(body))
            .query_param(Parameter()
                         .key("expand")
                         .value(expand))
            .header_param(Parameter()
                          .key("accept")
                          .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(And(Single("user-id"), Single("user-api-key"),
                Single("developer-id"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ResponseTransaction.from_dictionary)
            .is_api_response(True)
            .local_error("401", "Unauthorized", Response401tokenException)
            .local_error("412", "Precondition Failed", Response412Exception),
        ).execute()

    def auth_complete(self,
                      transaction_id,
                      body,
                      expand=None):
        """Perform a PATCH request to /v1/transactions/{transaction_id}/auth-complete.

        Perform an auth complete transaction

        Args:
            transaction_id (str): Transaction ID
            body (V1TransactionsAuthCompleteRequest): The request body
                parameter.
            expand (List[Expand54Enum], optional): Most endpoints in the API
                have a way to retrieve extra data related to the current
                record being retrieved. For example, if the API request is for
                the accountvaults endpoint, and the end user also needs to
                know which contact the token belongs to, this data can be
                returned in the accountvaults endpoint request.

        Returns:
            ApiResponse: An object with the response value as well as other
                useful information such as status codes and headers. OK

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/transactions/{transaction_id}/auth-complete")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                            .key("transaction_id")
                            .value(transaction_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key("Content-Type")
                          .value("application/json"))
            .body_param(Parameter()
                        .value(body))
            .query_param(Parameter()
                         .key("expand")
                         .value(expand))
            .header_param(Parameter()
                          .key("accept")
                          .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(And(Single("user-id"), Single("user-api-key"),
                Single("developer-id"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ResponseTransaction.from_dictionary)
            .is_api_response(True)
            .local_error("401", "Unauthorized", Response401tokenException)
            .local_error("412", "Precondition Failed", Response412Exception),
        ).execute()

    def auth_increment(self,
                       transaction_id,
                       body,
                       expand=None):
        """Perform a PATCH request to
        /v1/transactions/{transaction_id}/auth-increment.

        Perform an auth increment transaction

        Args:
            transaction_id (str): Transaction ID
            body (V1TransactionsAuthIncrementRequest): The request body
                parameter.
            expand (List[Expand54Enum], optional): Most endpoints in the API
                have a way to retrieve extra data related to the current
                record being retrieved. For example, if the API request is for
                the accountvaults endpoint, and the end user also needs to
                know which contact the token belongs to, this data can be
                returned in the accountvaults endpoint request.

        Returns:
            ApiResponse: An object with the response value as well as other
                useful information such as status codes and headers. OK

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/transactions/{transaction_id}/auth-increment")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                            .key("transaction_id")
                            .value(transaction_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key("Content-Type")
                          .value("application/json"))
            .body_param(Parameter()
                        .value(body))
            .query_param(Parameter()
                         .key("expand")
                         .value(expand))
            .header_param(Parameter()
                          .key("accept")
                          .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(And(Single("user-id"), Single("user-api-key"),
                Single("developer-id"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ResponseTransaction.from_dictionary)
            .is_api_response(True)
            .local_error("401", "Unauthorized", Response401tokenException)
            .local_error("412", "Precondition Failed", Response412Exception),
        ).execute()

    def partial_reversal(self,
                         transaction_id,
                         body,
                         expand=None):
        """Perform a PATCH request to
        /v1/transactions/{transaction_id}/partial-reversal.

        Perform a partial reversal

        Args:
            transaction_id (str): Transaction ID
            body (V1TransactionsPartialReversalRequest): The request body
                parameter.
            expand (List[Expand54Enum], optional): Most endpoints in the API
                have a way to retrieve extra data related to the current
                record being retrieved. For example, if the API request is for
                the accountvaults endpoint, and the end user also needs to
                know which contact the token belongs to, this data can be
                returned in the accountvaults endpoint request.

        Returns:
            ApiResponse: An object with the response value as well as other
                useful information such as status codes and headers. OK

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/transactions/{transaction_id}/partial-reversal")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                            .key("transaction_id")
                            .value(transaction_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key("Content-Type")
                          .value("application/json"))
            .body_param(Parameter()
                        .value(body))
            .query_param(Parameter()
                         .key("expand")
                         .value(expand))
            .header_param(Parameter()
                          .key("accept")
                          .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(And(Single("user-id"), Single("user-api-key"),
                Single("developer-id"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ResponseTransaction.from_dictionary)
            .is_api_response(True)
            .local_error("401", "Unauthorized", Response401tokenException)
            .local_error("412", "Precondition Failed", Response412Exception),
        ).execute()

    def refund_transaction(self,
                           transaction_id,
                           body,
                           expand=None):
        """Perform a PATCH request to /v1/transactions/{transaction_id}/refund.

        Perform a refund transaction

        Args:
            transaction_id (str): Transaction ID
            body (V1TransactionsRefundRequest): The request body parameter.
            expand (List[Expand54Enum], optional): Most endpoints in the API
                have a way to retrieve extra data related to the current
                record being retrieved. For example, if the API request is for
                the accountvaults endpoint, and the end user also needs to
                know which contact the token belongs to, this data can be
                returned in the accountvaults endpoint request.

        Returns:
            ApiResponse: An object with the response value as well as other
                useful information such as status codes and headers. OK

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/transactions/{transaction_id}/refund")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                            .key("transaction_id")
                            .value(transaction_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key("Content-Type")
                          .value("application/json"))
            .body_param(Parameter()
                        .value(body))
            .query_param(Parameter()
                         .key("expand")
                         .value(expand))
            .header_param(Parameter()
                          .key("accept")
                          .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(And(Single("user-id"), Single("user-api-key"),
                Single("developer-id"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ResponseTransaction.from_dictionary)
            .is_api_response(True)
            .local_error("401", "Unauthorized", Response401tokenException)
            .local_error("412", "Precondition Failed", Response412Exception),
        ).execute()

    def tip_adjustment(self,
                       transaction_id,
                       body,
                       expand=None):
        """Perform a PATCH request to /v1/transactions/{transaction_id}/tip-adjust.

        Increment the authorized transaction amount to include a tip

        Args:
            transaction_id (str): Transaction ID
            body (V1TransactionsTipAdjustRequest): The request body parameter.
            expand (List[Expand54Enum], optional): Most endpoints in the API
                have a way to retrieve extra data related to the current
                record being retrieved. For example, if the API request is for
                the accountvaults endpoint, and the end user also needs to
                know which contact the token belongs to, this data can be
                returned in the accountvaults endpoint request.

        Returns:
            ApiResponse: An object with the response value as well as other
                useful information such as status codes and headers. OK

        Raises:
            APIException: When an error occurs while fetching the data from
                the remote API. This exception includes the HTTP Response
                code, an error message, and the HTTP body that was received in
                the request.

        """
        return super().new_api_call_builder.request(
            RequestBuilder().server(Server.DEFAULT)
            .path("/v1/transactions/{transaction_id}/tip-adjust")
            .http_method(HttpMethodEnum.PATCH)
            .template_param(Parameter()
                            .key("transaction_id")
                            .value(transaction_id)
                            .should_encode(True))
            .header_param(Parameter()
                          .key("Content-Type")
                          .value("application/json"))
            .body_param(Parameter()
                        .value(body))
            .query_param(Parameter()
                         .key("expand")
                         .value(expand))
            .header_param(Parameter()
                          .key("accept")
                          .value("application/json"))
            .body_serializer(APIHelper.json_serialize)
            .auth(And(Single("user-id"), Single("user-api-key"),
                Single("developer-id"))),
        ).response(
            ResponseHandler()
            .deserializer(APIHelper.json_deserialize)
            .deserialize_into(ResponseTransaction.from_dictionary)
            .is_api_response(True)
            .local_error("401", "Unauthorized", Response401tokenException)
            .local_error("412", "Precondition Failed", Response412Exception),
        ).execute()
