# -*- coding: utf-8 -*-

"""
fortisapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Expand1Enum(object):

    """Implementation of the 'expand1' enum.

    Attributes:
        RECEIVED_EMAILS: The enum member of type str.
        IS_DELETABLE: The enum member of type str.
        LOCATION: The enum member of type str.
        USER: The enum member of type str.
        RECURRINGS: The enum member of type str.
        EMAIL_BLACKLIST: The enum member of type str.
        SMS_BLACKLIST: The enum member of type str.
        CHANGELOGS: The enum member of type str.
        POSTBACK_LOGS: The enum member of type str.
        CREATED_USER: The enum member of type str.
        PARENT: The enum member of type str.
        CHILDREN: The enum member of type str.
        additional_properties (Dict[str, object]): The additional properties
            for the model.

    """
    RECEIVED_EMAILS = 'received_emails'

    IS_DELETABLE = 'is_deletable'

    LOCATION = 'location'

    USER = 'user'

    RECURRINGS = 'recurrings'

    EMAIL_BLACKLIST = 'email_blacklist'

    SMS_BLACKLIST = 'sms_blacklist'

    CHANGELOGS = 'changelogs'

    POSTBACK_LOGS = 'postback_logs'

    CREATED_USER = 'created_user'

    PARENT = 'parent'

    CHILDREN = 'children'

    @classmethod
    def from_value(cls, value, default=None):
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
