"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""


class Field45Enum(object):
    """Implementation of the 'field45' enum.

    Attributes:
        LOCATION_ID: The enum member of type str.
        DEFAULT_PRODUCT_TRANSACTION_ID: The enum member of type str.
        TERMINAL_APPLICATION_ID: The enum member of type str.
        TERMINAL_CVM_ID: The enum member of type str.
        TERMINAL_MANUFACTURER_CODE: The enum member of type str.
        TITLE: The enum member of type str.
        MAC_ADDRESS: The enum member of type str.
        LOCAL_IP_ADDRESS: The enum member of type str.
        PORT: The enum member of type str.
        SERIAL_NUMBER: The enum member of type str.
        TERMINAL_NUMBER: The enum member of type str.
        TERMINAL_TIMEOUTS: The enum member of type str.
        TIP_PERCENTS: The enum member of type str.
        LOCATION_API_ID: The enum member of type str.
        TERMINAL_API_ID: The enum member of type str.
        HEADER_LINE_1: The enum member of type str.
        HEADER_LINE_2: The enum member of type str.
        HEADER_LINE_3: The enum member of type str.
        HEADER_LINE_4: The enum member of type str.
        HEADER_LINE_5: The enum member of type str.
        TRAILER_LINE_1: The enum member of type str.
        TRAILER_LINE_2: The enum member of type str.
        TRAILER_LINE_3: The enum member of type str.
        TRAILER_LINE_4: The enum member of type str.
        TRAILER_LINE_5: The enum member of type str.
        DEFAULT_CHECKIN: The enum member of type str.
        DEFAULT_CHECKOUT: The enum member of type str.
        DEFAULT_ROOM_RATE: The enum member of type str.
        DEFAULT_ROOM_NUMBER: The enum member of type str.
        DEBIT: The enum member of type str.
        EMV: The enum member of type str.
        CASHBACK_ENABLE: The enum member of type str.
        PRINT_ENABLE: The enum member of type str.
        SIG_CAPTURE_ENABLE: The enum member of type str.
        IS_PROVISIONED: The enum member of type str.
        TIP_ENABLE: The enum member of type str.
        VALIDATED_DECRYPTION: The enum member of type str.
        COMMUNICATION_TYPE: The enum member of type str.
        ACTIVE: The enum member of type str.
        ID: The enum member of type str.
        CREATED_TS: The enum member of type str.
        MODIFIED_TS: The enum member of type str.
        LAST_REGISTRATION_TS: The enum member of type str.
        CREATED_USER_ID: The enum member of type str.
        MODIFIED_USER_ID: The enum member of type str.
        LOCATION: The enum member of type str.
        CREATED_USER: The enum member of type str.
        TERMINAL_APPLICATION: The enum member of type str.
        CHANGELOGS: The enum member of type str.
        TERMINAL_ROUTERS: The enum member of type str.
        HAS_TERMINAL_ROUTERS: The enum member of type str.
        TERMINAL_CVM: The enum member of type str.
        TERMINAL_MANUFACTURER: The enum member of type str.
        additional_properties (Dict[str, object]): The additional properties
            for the model.

    """

    LOCATION_ID = "location_id"

    DEFAULT_PRODUCT_TRANSACTION_ID = "default_product_transaction_id"

    TERMINAL_APPLICATION_ID = "terminal_application_id"

    TERMINAL_CVM_ID = "terminal_cvm_id"

    TERMINAL_MANUFACTURER_CODE = "terminal_manufacturer_code"

    TITLE = "title"

    MAC_ADDRESS = "mac_address"

    LOCAL_IP_ADDRESS = "local_ip_address"

    PORT = "port"

    SERIAL_NUMBER = "serial_number"

    TERMINAL_NUMBER = "terminal_number"

    TERMINAL_TIMEOUTS = "terminal_timeouts"

    TIP_PERCENTS = "tip_percents"

    LOCATION_API_ID = "location_api_id"

    TERMINAL_API_ID = "terminal_api_id"

    HEADER_LINE_1 = "header_line_1"

    HEADER_LINE_2 = "header_line_2"

    HEADER_LINE_3 = "header_line_3"

    HEADER_LINE_4 = "header_line_4"

    HEADER_LINE_5 = "header_line_5"

    TRAILER_LINE_1 = "trailer_line_1"

    TRAILER_LINE_2 = "trailer_line_2"

    TRAILER_LINE_3 = "trailer_line_3"

    TRAILER_LINE_4 = "trailer_line_4"

    TRAILER_LINE_5 = "trailer_line_5"

    DEFAULT_CHECKIN = "default_checkin"

    DEFAULT_CHECKOUT = "default_checkout"

    DEFAULT_ROOM_RATE = "default_room_rate"

    DEFAULT_ROOM_NUMBER = "default_room_number"

    DEBIT = "debit"

    EMV = "emv"

    CASHBACK_ENABLE = "cashback_enable"

    PRINT_ENABLE = "print_enable"

    SIG_CAPTURE_ENABLE = "sig_capture_enable"

    IS_PROVISIONED = "is_provisioned"

    TIP_ENABLE = "tip_enable"

    VALIDATED_DECRYPTION = "validated_decryption"

    COMMUNICATION_TYPE = "communication_type"

    ACTIVE = "active"

    ID = "id"

    CREATED_TS = "created_ts"

    MODIFIED_TS = "modified_ts"

    LAST_REGISTRATION_TS = "last_registration_ts"

    CREATED_USER_ID = "created_user_id"

    MODIFIED_USER_ID = "modified_user_id"

    LOCATION = "location"

    CREATED_USER = "created_user"

    TERMINAL_APPLICATION = "terminal_application"

    CHANGELOGS = "changelogs"

    TERMINAL_ROUTERS = "terminal_routers"

    HAS_TERMINAL_ROUTERS = "has_terminal_routers"

    TERMINAL_CVM = "terminal_cvm"

    TERMINAL_MANUFACTURER = "terminal_manufacturer"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
