"""fortisapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""


class Field26Enum(object):
    """Implementation of the 'field26' enum.

    Attributes:
        LOCATION_ID: The enum member of type str.
        ACCOUNT_NUMBER: The enum member of type str.
        CONTACT_API_ID: The enum member of type str.
        FIRST_NAME: The enum member of type str.
        LAST_NAME: The enum member of type str.
        CELL_PHONE: The enum member of type str.
        BALANCE: The enum member of type str.
        ADDRESS: The enum member of type str.
        COMPANY_NAME: The enum member of type str.
        HEADER_MESSAGE: The enum member of type str.
        DATE_OF_BIRTH: The enum member of type str.
        EMAIL_TRX_RECEIPT: The enum member of type str.
        HOME_PHONE: The enum member of type str.
        OFFICE_PHONE: The enum member of type str.
        OFFICE_PHONE_EXT: The enum member of type str.
        HEADER_MESSAGE_TYPE: The enum member of type str.
        UPDATE_IF_EXISTS: The enum member of type str.
        CONTACT_C1: The enum member of type str.
        CONTACT_C2: The enum member of type str.
        CONTACT_C3: The enum member of type str.
        PARENT_ID: The enum member of type str.
        EMAIL: The enum member of type str.
        ID: The enum member of type str.
        CREATED_TS: The enum member of type str.
        MODIFIED_TS: The enum member of type str.
        ACTIVE: The enum member of type str.
        CREATED_USER_ID: The enum member of type str.
        RECEIVED_EMAILS: The enum member of type str.
        IS_DELETABLE: The enum member of type str.
        LOCATION: The enum member of type str.
        USER: The enum member of type str.
        RECURRINGS: The enum member of type str.
        EMAIL_BLACKLIST: The enum member of type str.
        SMS_BLACKLIST: The enum member of type str.
        CHANGELOGS: The enum member of type str.
        POSTBACK_LOGS: The enum member of type str.
        CREATED_USER: The enum member of type str.
        PARENT: The enum member of type str.
        CHILDREN: The enum member of type str.
        additional_properties (Dict[str, object]): The additional properties
            for the model.

    """

    LOCATION_ID = "location_id"

    ACCOUNT_NUMBER = "account_number"

    CONTACT_API_ID = "contact_api_id"

    FIRST_NAME = "first_name"

    LAST_NAME = "last_name"

    CELL_PHONE = "cell_phone"

    BALANCE = "balance"

    ADDRESS = "address"

    COMPANY_NAME = "company_name"

    HEADER_MESSAGE = "header_message"

    DATE_OF_BIRTH = "date_of_birth"

    EMAIL_TRX_RECEIPT = "email_trx_receipt"

    HOME_PHONE = "home_phone"

    OFFICE_PHONE = "office_phone"

    OFFICE_PHONE_EXT = "office_phone_ext"

    HEADER_MESSAGE_TYPE = "header_message_type"

    UPDATE_IF_EXISTS = "update_if_exists"

    CONTACT_C1 = "contact_c1"

    CONTACT_C2 = "contact_c2"

    CONTACT_C3 = "contact_c3"

    PARENT_ID = "parent_id"

    EMAIL = "email"

    ID = "id"

    CREATED_TS = "created_ts"

    MODIFIED_TS = "modified_ts"

    ACTIVE = "active"

    CREATED_USER_ID = "created_user_id"

    RECEIVED_EMAILS = "received_emails"

    IS_DELETABLE = "is_deletable"

    LOCATION = "location"

    USER = "user"

    RECURRINGS = "recurrings"

    EMAIL_BLACKLIST = "email_blacklist"

    SMS_BLACKLIST = "sms_blacklist"

    CHANGELOGS = "changelogs"

    POSTBACK_LOGS = "postback_logs"

    CREATED_USER = "created_user"

    PARENT = "parent"

    CHILDREN = "children"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
