# -*- coding: utf-8 -*-

"""
fortisapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class IiasIndEnum(object):

    """Implementation of the 'IiasInd' enum.

    Possible values are '0', '1','2'

    Attributes:
        ENUM_0: The enum member of type int.
        ENUM_1: The enum member of type int.
        ENUM_2: The enum member of type int.
        additional_properties (Dict[str, object]): The additional properties
            for the model.

    """
    _all_values = [0, 1, 2]
    ENUM_0 = 0

    ENUM_1 = 1

    ENUM_2 = 2

    @classmethod
    def validate(cls, value):
        """Validates value contains in enum

        Args:
            value: the value to be validated

        Returns:
            boolean : if value is valid enum values.

        """
        return value in cls._all_values
   
    @classmethod
    def from_value(cls, value, default=None):
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
