# -*- coding: utf-8 -*-

"""
fortisapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from fortisapi.api_helper import APIHelper


class List17(object):

    """Implementation of the 'List17' model.

    Attributes:
        id (str): The model property of type str.
        user_id (str): The model property of type str.
        hash (str): The model property of type str.
        created_ts (int): Created Time Stamp
        additional_properties (Dict[str, object]): The additional properties
            for the model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "user_id": 'user_id',
        "hash": 'hash',
        "created_ts": 'created_ts'
    }

    _optionals = [
        'id',
        'user_id',
        'hash',
        'created_ts',
    ]

    def __init__(self,
                 id=APIHelper.SKIP,
                 user_id=APIHelper.SKIP,
                 hash=APIHelper.SKIP,
                 created_ts=APIHelper.SKIP,
                 additional_properties=None):
        """Constructor for the List17 class"""

        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id 
        if user_id is not APIHelper.SKIP:
            self.user_id = user_id 
        if hash is not APIHelper.SKIP:
            self.hash = hash 
        if created_ts is not APIHelper.SKIP:
            self.created_ts = created_ts 

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        user_id = dictionary.get("user_id") if dictionary.get("user_id") else APIHelper.SKIP
        hash = dictionary.get("hash") if dictionary.get("hash") else APIHelper.SKIP
        created_ts = dictionary.get("created_ts") if dictionary.get("created_ts") else APIHelper.SKIP
        # Clean out expected properties from dictionary
        additional_properties = {k: v for k, v in dictionary.items() if k not in cls._names.values()}
        # Return an object of this model
        return cls(id,
                   user_id,
                   hash,
                   created_ts,
                   additional_properties)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!r}, '
                f'user_id={(self.user_id if hasattr(self, "user_id") else None)!r}, '
                f'hash={(self.hash if hasattr(self, "hash") else None)!r}, '
                f'created_ts={(self.created_ts if hasattr(self, "created_ts") else None)!r}, '
                f'additional_properties={self.additional_properties!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'id={(self.id if hasattr(self, "id") else None)!s}, '
                f'user_id={(self.user_id if hasattr(self, "user_id") else None)!s}, '
                f'hash={(self.hash if hasattr(self, "hash") else None)!s}, '
                f'created_ts={(self.created_ts if hasattr(self, "created_ts") else None)!s}, '
                f'additional_properties={self.additional_properties!s})')
