# -*- coding: utf-8 -*-

"""
fortisapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusCode17Enum(object):

    """Implementation of the 'StatusCode17' enum.

    Status ID - See status id section for more detail
    >101 - Sale cc Approved
    >
    >102 - Sale cc AuthOnly
    >
    >111 - Refund cc Refunded
    >
    >121 - Credit/Debit/Refund cc AvsOnly
    >
    >131 - Credit/Debit/Refund ach Pending Origination
    >
    >132 - Credit/Debit/Refund ach Originating
    >
    >133 - Credit/Debit/Refund ach Originated
    >
    >134 - Credit/Debit/Refund ach Settled
    >
    >191 - Settled (depracated - batches are now settled on the
    /v2/transactionbatches endpoint)
    >
    >201 - All cc/ach Voided
    >
    >301 - All cc/ach Declined
    >
    >331 - Credit/Debit/Refund ach Charged Back
    >

    Attributes:
        ENUM_101: The enum member of type int.
        ENUM_102: The enum member of type int.
        ENUM_111: The enum member of type int.
        ENUM_121: The enum member of type int.
        ENUM_131: The enum member of type int.
        ENUM_132: The enum member of type int.
        ENUM_133: The enum member of type int.
        ENUM_134: The enum member of type int.
        ENUM_191: The enum member of type int.
        ENUM_201: The enum member of type int.
        ENUM_301: The enum member of type int.
        ENUM_331: The enum member of type int.
        additional_properties (Dict[str, object]): The additional properties
            for the model.

    """
    ENUM_101 = 101

    ENUM_102 = 102

    ENUM_111 = 111

    ENUM_121 = 121

    ENUM_131 = 131

    ENUM_132 = 132

    ENUM_133 = 133

    ENUM_134 = 134

    ENUM_191 = 191

    ENUM_201 = 201

    ENUM_301 = 301

    ENUM_331 = 331

    @classmethod
    def from_value(cls, value, default=None):
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
