# -*- coding: utf-8 -*-

"""
fortisapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from fortisapi.api_helper import APIHelper


class TerminalCvm(object):

    """Implementation of the 'TerminalCvm' model.

    Terminal Cvm Information on `expand`

    Attributes:
        terminal_manufacturer_code (float): Terminal Manufacturer Code
        title (str): Title
        contact_data (str): Contact Data
        contactless_data (str): Contactless Data
        id (str): Terminal Manufacturer Cvms Id
        created_ts (int): Created Time Stamp
        modified_ts (int): Modified Time Stamp
        created_user_id (str): User ID Created the register
        modified_user_id (str): Last User ID that updated the register
        additional_properties (Dict[str, object]): The additional properties
            for the model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "terminal_manufacturer_code": 'terminal_manufacturer_code',
        "title": 'title',
        "contact_data": 'contact_data',
        "contactless_data": 'contactless_data',
        "id": 'id',
        "created_ts": 'created_ts',
        "modified_ts": 'modified_ts',
        "created_user_id": 'created_user_id',
        "modified_user_id": 'modified_user_id'
    }

    _optionals = [
        'terminal_manufacturer_code',
        'title',
        'contact_data',
        'contactless_data',
        'id',
        'created_ts',
        'modified_ts',
        'created_user_id',
        'modified_user_id',
    ]

    _nullables = [
        'contact_data',
        'contactless_data',
    ]

    def __init__(self,
                 terminal_manufacturer_code=APIHelper.SKIP,
                 title=APIHelper.SKIP,
                 contact_data=APIHelper.SKIP,
                 contactless_data=APIHelper.SKIP,
                 id=APIHelper.SKIP,
                 created_ts=APIHelper.SKIP,
                 modified_ts=APIHelper.SKIP,
                 created_user_id=APIHelper.SKIP,
                 modified_user_id=APIHelper.SKIP,
                 additional_properties=None):
        """Constructor for the TerminalCvm class"""

        # Initialize members of the class
        if terminal_manufacturer_code is not APIHelper.SKIP:
            self.terminal_manufacturer_code = terminal_manufacturer_code 
        if title is not APIHelper.SKIP:
            self.title = title 
        if contact_data is not APIHelper.SKIP:
            self.contact_data = contact_data 
        if contactless_data is not APIHelper.SKIP:
            self.contactless_data = contactless_data 
        if id is not APIHelper.SKIP:
            self.id = id 
        if created_ts is not APIHelper.SKIP:
            self.created_ts = created_ts 
        if modified_ts is not APIHelper.SKIP:
            self.modified_ts = modified_ts 
        if created_user_id is not APIHelper.SKIP:
            self.created_user_id = created_user_id 
        if modified_user_id is not APIHelper.SKIP:
            self.modified_user_id = modified_user_id 

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        terminal_manufacturer_code = dictionary.get("terminal_manufacturer_code") if dictionary.get("terminal_manufacturer_code") else APIHelper.SKIP
        title = dictionary.get("title") if dictionary.get("title") else APIHelper.SKIP
        contact_data = dictionary.get("contact_data") if "contact_data" in dictionary.keys() else APIHelper.SKIP
        contactless_data = dictionary.get("contactless_data") if "contactless_data" in dictionary.keys() else APIHelper.SKIP
        id = dictionary.get("id") if dictionary.get("id") else APIHelper.SKIP
        created_ts = dictionary.get("created_ts") if dictionary.get("created_ts") else APIHelper.SKIP
        modified_ts = dictionary.get("modified_ts") if dictionary.get("modified_ts") else APIHelper.SKIP
        created_user_id = dictionary.get("created_user_id") if dictionary.get("created_user_id") else APIHelper.SKIP
        modified_user_id = dictionary.get("modified_user_id") if dictionary.get("modified_user_id") else APIHelper.SKIP
        # Clean out expected properties from dictionary
        additional_properties = {k: v for k, v in dictionary.items() if k not in cls._names.values()}
        # Return an object of this model
        return cls(terminal_manufacturer_code,
                   title,
                   contact_data,
                   contactless_data,
                   id,
                   created_ts,
                   modified_ts,
                   created_user_id,
                   modified_user_id,
                   additional_properties)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'terminal_manufacturer_code={(self.terminal_manufacturer_code if hasattr(self, "terminal_manufacturer_code") else None)!r}, '
                f'title={(self.title if hasattr(self, "title") else None)!r}, '
                f'contact_data={(self.contact_data if hasattr(self, "contact_data") else None)!r}, '
                f'contactless_data={(self.contactless_data if hasattr(self, "contactless_data") else None)!r}, '
                f'id={(self.id if hasattr(self, "id") else None)!r}, '
                f'created_ts={(self.created_ts if hasattr(self, "created_ts") else None)!r}, '
                f'modified_ts={(self.modified_ts if hasattr(self, "modified_ts") else None)!r}, '
                f'created_user_id={(self.created_user_id if hasattr(self, "created_user_id") else None)!r}, '
                f'modified_user_id={(self.modified_user_id if hasattr(self, "modified_user_id") else None)!r}, '
                f'additional_properties={self.additional_properties!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'terminal_manufacturer_code={(self.terminal_manufacturer_code if hasattr(self, "terminal_manufacturer_code") else None)!s}, '
                f'title={(self.title if hasattr(self, "title") else None)!s}, '
                f'contact_data={(self.contact_data if hasattr(self, "contact_data") else None)!s}, '
                f'contactless_data={(self.contactless_data if hasattr(self, "contactless_data") else None)!s}, '
                f'id={(self.id if hasattr(self, "id") else None)!s}, '
                f'created_ts={(self.created_ts if hasattr(self, "created_ts") else None)!s}, '
                f'modified_ts={(self.modified_ts if hasattr(self, "modified_ts") else None)!s}, '
                f'created_user_id={(self.created_user_id if hasattr(self, "created_user_id") else None)!s}, '
                f'modified_user_id={(self.modified_user_id if hasattr(self, "modified_user_id") else None)!s}, '
                f'additional_properties={self.additional_properties!s})')
