# -*- coding: utf-8 -*-

"""
greenbyteapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from greenbyteapi.api_helper import APIHelper


class HseIncidentsResponse(object):

    """Implementation of the 'Hse Incidents Response' model.

    An HSE incident.

    Attributes:
        hse_incident_id (int): The id of an HSE incident.
        site_id (int): The id of a site.
        device_id (int): The id of a device.
        timestamp (datetime): The timestamp when the incident occurred. The
            timestamp is in the time zone configured in the Greenbyte Platform
            without UTC offset.
        hse_category (HSECategoryEnum): The category of an HSE incident.
        lost_time_injury (bool): Whether or not the incident resulted in an
            injury sustained on the job, causing loss of productive work time.
        incident_description (str): The description related to the incident.
        resolved (bool): Whether or not the incident has been resolved.
        resolved_timestamp (datetime): The timestamp when the incident has
            been resolved.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "hse_incident_id": 'hseIncidentId',
        "site_id": 'siteId',
        "device_id": 'deviceId',
        "timestamp": 'timestamp',
        "hse_category": 'hseCategory',
        "lost_time_injury": 'lostTimeInjury',
        "incident_description": 'incidentDescription',
        "resolved": 'resolved',
        "resolved_timestamp": 'resolvedTimestamp'
    }

    _optionals = [
        'hse_incident_id',
        'site_id',
        'device_id',
        'timestamp',
        'hse_category',
        'lost_time_injury',
        'incident_description',
        'resolved',
        'resolved_timestamp',
    ]

    _nullables = [
        'incident_description',
        'resolved_timestamp',
    ]

    def __init__(self,
                 hse_incident_id=APIHelper.SKIP,
                 site_id=APIHelper.SKIP,
                 device_id=APIHelper.SKIP,
                 timestamp=APIHelper.SKIP,
                 hse_category=APIHelper.SKIP,
                 lost_time_injury=False,
                 incident_description=APIHelper.SKIP,
                 resolved=False,
                 resolved_timestamp=APIHelper.SKIP):
        """Constructor for the HseIncidentsResponse class"""

        # Initialize members of the class
        if hse_incident_id is not APIHelper.SKIP:
            self.hse_incident_id = hse_incident_id 
        if site_id is not APIHelper.SKIP:
            self.site_id = site_id 
        if device_id is not APIHelper.SKIP:
            self.device_id = device_id 
        if timestamp is not APIHelper.SKIP:
            self.timestamp = APIHelper.apply_datetime_converter(timestamp, APIHelper.RFC3339DateTime) if timestamp else None 
        if hse_category is not APIHelper.SKIP:
            self.hse_category = hse_category 
        self.lost_time_injury = lost_time_injury 
        if incident_description is not APIHelper.SKIP:
            self.incident_description = incident_description 
        self.resolved = resolved 
        if resolved_timestamp is not APIHelper.SKIP:
            self.resolved_timestamp = APIHelper.apply_datetime_converter(resolved_timestamp, APIHelper.RFC3339DateTime) if resolved_timestamp else None 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        hse_incident_id = dictionary.get("hseIncidentId") if dictionary.get("hseIncidentId") else APIHelper.SKIP
        site_id = dictionary.get("siteId") if dictionary.get("siteId") else APIHelper.SKIP
        device_id = dictionary.get("deviceId") if dictionary.get("deviceId") else APIHelper.SKIP
        timestamp = APIHelper.RFC3339DateTime.from_value(dictionary.get("timestamp")).datetime if dictionary.get("timestamp") else APIHelper.SKIP
        hse_category = dictionary.get("hseCategory") if dictionary.get("hseCategory") else APIHelper.SKIP
        lost_time_injury = dictionary.get("lostTimeInjury") if dictionary.get("lostTimeInjury") else False
        incident_description = dictionary.get("incidentDescription") if "incidentDescription" in dictionary.keys() else APIHelper.SKIP
        resolved = dictionary.get("resolved") if dictionary.get("resolved") else False
        if 'resolvedTimestamp' in dictionary.keys():
            resolved_timestamp = APIHelper.RFC3339DateTime.from_value(dictionary.get("resolvedTimestamp")).datetime if dictionary.get("resolvedTimestamp") else None
        else:
            resolved_timestamp = APIHelper.SKIP
        # Return an object of this model
        return cls(hse_incident_id,
                   site_id,
                   device_id,
                   timestamp,
                   hse_category,
                   lost_time_injury,
                   incident_description,
                   resolved,
                   resolved_timestamp)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'hse_incident_id={(self.hse_incident_id if hasattr(self, "hse_incident_id") else None)!r}, '
                f'site_id={(self.site_id if hasattr(self, "site_id") else None)!r}, '
                f'device_id={(self.device_id if hasattr(self, "device_id") else None)!r}, '
                f'timestamp={(self.timestamp if hasattr(self, "timestamp") else None)!r}, '
                f'hse_category={(self.hse_category if hasattr(self, "hse_category") else None)!r}, '
                f'lost_time_injury={(self.lost_time_injury if hasattr(self, "lost_time_injury") else None)!r}, '
                f'incident_description={(self.incident_description if hasattr(self, "incident_description") else None)!r}, '
                f'resolved={(self.resolved if hasattr(self, "resolved") else None)!r}, '
                f'resolved_timestamp={(self.resolved_timestamp if hasattr(self, "resolved_timestamp") else None)!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'hse_incident_id={(self.hse_incident_id if hasattr(self, "hse_incident_id") else None)!s}, '
                f'site_id={(self.site_id if hasattr(self, "site_id") else None)!s}, '
                f'device_id={(self.device_id if hasattr(self, "device_id") else None)!s}, '
                f'timestamp={(self.timestamp if hasattr(self, "timestamp") else None)!s}, '
                f'hse_category={(self.hse_category if hasattr(self, "hse_category") else None)!s}, '
                f'lost_time_injury={(self.lost_time_injury if hasattr(self, "lost_time_injury") else None)!s}, '
                f'incident_description={(self.incident_description if hasattr(self, "incident_description") else None)!s}, '
                f'resolved={(self.resolved if hasattr(self, "resolved") else None)!s}, '
                f'resolved_timestamp={(self.resolved_timestamp if hasattr(self, "resolved_timestamp") else None)!s})')
