"""payfacsubmerchantprovisioningapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from payfacsubmerchantprovisioningapi.api_helper import (
    APIHelper,
)
from payfacsubmerchantprovisioningapi.models.physical_address import (
    PhysicalAddress,
)
from payfacsubmerchantprovisioningapi.models.primary_contact import (
    PrimaryContact,
)


class DivisionsForPatch(object):
    """Implementation of the 'DivisionsForPatch' model.

    Attributes:
        division_name (str): Division name for the division
        contact_data (PrimaryContact): The model property of type
            PrimaryContact.
        address_data (PhysicalAddress): The model property of type
            PhysicalAddress.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "division_name": "divisionName",
        "contact_data": "contactData",
        "address_data": "addressData",
    }

    _optionals = [
        "division_name",
        "contact_data",
        "address_data",
    ]

    def __init__(self,
                 division_name=APIHelper.SKIP,
                 contact_data=APIHelper.SKIP,
                 address_data=APIHelper.SKIP):
        """Initialize a DivisionsForPatch instance."""
        # Initialize members of the class
        if division_name is not APIHelper.SKIP:
            self.division_name = division_name
        if contact_data is not APIHelper.SKIP:
            self.contact_data = contact_data
        if address_data is not APIHelper.SKIP:
            self.address_data = address_data

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        division_name =\
            dictionary.get("divisionName")\
            if dictionary.get("divisionName") else APIHelper.SKIP
        contact_data = PrimaryContact.from_dictionary(
            dictionary.get("contactData"))\
            if "contactData" in dictionary.keys() else APIHelper.SKIP
        address_data = PhysicalAddress.from_dictionary(
            dictionary.get("addressData"))\
            if "addressData" in dictionary.keys() else APIHelper.SKIP
        # Return an object of this model
        return cls(division_name,
                   contact_data,
                   address_data)

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"division_name={(self.division_name
                     if hasattr(self, 'division_name') else None)!r}, "
                f"contact_data={(self.contact_data
                     if hasattr(self, 'contact_data') else None)!r}, "
                f"address_data={(self.address_data
                     if hasattr(self, 'address_data') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"division_name={(self.division_name
                     if hasattr(self, 'division_name') else None)!s}, "
                f"contact_data={(self.contact_data
                     if hasattr(self, 'contact_data') else None)!s}, "
                f"address_data={(self.address_data
                     if hasattr(self, 'address_data') else None)!s})")
