"""payfacsubmerchantprovisioningapi.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

from payfacsubmerchantprovisioningapi.api_helper import (
    APIHelper,
)


class TerminalToCreate(object):
    """Implementation of the 'TerminalToCreate' model.

    Attributes:
        template_mid (str): Template Mid associated with the chain code - used
            for building terminals
        tid (str): The model property of type str.
        quantity (str): The model property of type str.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "template_mid": "templateMid",
        "tid": "tid",
        "quantity": "quantity",
    }

    _optionals = [
        "template_mid",
        "tid",
        "quantity",
    ]

    def __init__(self,
                 template_mid=APIHelper.SKIP,
                 tid=APIHelper.SKIP,
                 quantity=APIHelper.SKIP):
        """Initialize a TerminalToCreate instance."""
        # Initialize members of the class
        if template_mid is not APIHelper.SKIP:
            self.template_mid = template_mid
        if tid is not APIHelper.SKIP:
            self.tid = tid
        if quantity is not APIHelper.SKIP:
            self.quantity = quantity

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        template_mid =\
            dictionary.get("templateMid")\
            if dictionary.get("templateMid") else APIHelper.SKIP
        tid = dictionary.get("tid") if dictionary.get("tid") else APIHelper.SKIP
        quantity =\
            dictionary.get("quantity")\
            if dictionary.get("quantity") else APIHelper.SKIP
        # Return an object of this model
        return cls(template_mid,
                   tid,
                   quantity)

    def __repr__(self):
        """Return a unambiguous string representation."""
        return (f"{self.__class__.__name__}("
                f"template_mid={(self.template_mid
                     if hasattr(self, 'template_mid') else None)!r}, "
                f"tid={(self.tid if hasattr(self, 'tid') else None)!r}, "
                f"quantity={(self.quantity
                     if hasattr(self, 'quantity') else None)!r})")

    def __str__(self):
        """Return a human-readable string representation."""
        return (f"{self.__class__.__name__}("
                f"template_mid={(self.template_mid
                     if hasattr(self, 'template_mid') else None)!s}, "
                f"tid={(self.tid if hasattr(self, 'tid') else None)!s}, "
                f"quantity={(self.quantity
                     if hasattr(self, 'quantity') else None)!s})")
