# -*- coding: utf-8 -*-

"""
goeapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from goeapi.api_helper import APIHelper
from goeapi.models.goe_to_cashflow_details_2 import GoeToCashflowDetails2
from goeapi.models.goe_to_category import GoeToCategory


class GoeToAccountAttr(object):

    """Implementation of the 'GoeToAccountAttr' model.

    Attributes:
        account_id (str): Used to identify an account
        account_type (str): Defines the type of account given.                
            In the case of TDA and Roth accounts, the possible ‘accountType’
            are: “401k” and “IRA”. <br>                    In the case of
            Taxable account, ‘accountType’ does not exist and this field
            should be passed as null. <br>                    In future
            releases, the recommendations would be tuned to the ‘accountType’.
        taxability_type (str): Defines the nature of the account. <br>        
            “T”: taxable account <br>                        “D”: tax deferred
            account <br>                        “F”: Roth account
        member_i_ds (List[str]): List of member IDs that have claim over a
            single account. <br>                        It is recommended to
            have an aggregated “taxable” account for all members in the
            household. <br>                        In casethe case of tda /
            roth accounts, different members of a household can have different
            accounts. <br>                        For MVP, exactly one member
            should be passed in the request payload.
        current_balance (int): Account balance as of the current date
        current_holdings (List[GoeToCategory]): Details of the holdings in an
            account
        cashflow_details (GoeToCashflowDetails2): Details of infusions i.e.,
            money deposited in an account
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "account_id": 'accountID',
        "account_type": 'accountType',
        "taxability_type": 'taxabilityType',
        "member_i_ds": 'memberIDs',
        "current_balance": 'currentBalance',
        "current_holdings": 'currentHoldings',
        "cashflow_details": 'cashflowDetails'
    }

    _nullables = [
        'account_type',
    ]

    def __init__(self,
                 account_id=None,
                 account_type=None,
                 taxability_type=None,
                 member_i_ds=None,
                 current_balance=None,
                 current_holdings=None,
                 cashflow_details=None,
                 additional_properties=None):
        """Constructor for the GoeToAccountAttr class"""

        # Initialize members of the class
        self.account_id = account_id 
        self.account_type = account_type 
        self.taxability_type = taxability_type 
        self.member_i_ds = member_i_ds 
        self.current_balance = current_balance 
        self.current_holdings = current_holdings 
        self.cashflow_details = cashflow_details 

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        account_id = dictionary.get("accountID") if dictionary.get("accountID") else None
        account_type = dictionary.get("accountType") if dictionary.get("accountType") else None
        taxability_type = dictionary.get("taxabilityType") if dictionary.get("taxabilityType") else None
        member_i_ds = dictionary.get("memberIDs") if dictionary.get("memberIDs") else None
        current_balance = dictionary.get("currentBalance") if dictionary.get("currentBalance") else None
        current_holdings = None
        if dictionary.get('currentHoldings') is not None:
            current_holdings = [GoeToCategory.from_dictionary(x) for x in dictionary.get('currentHoldings')]
        cashflow_details = GoeToCashflowDetails2.from_dictionary(dictionary.get('cashflowDetails')) if dictionary.get('cashflowDetails') else None
        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items() if k not in cls._names.values()},
            unboxing_function=lambda value: value)
        # Return an object of this model
        return cls(account_id,
                   account_type,
                   taxability_type,
                   member_i_ds,
                   current_balance,
                   current_holdings,
                   cashflow_details,
                   additional_properties)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'account_id={self.account_id!r}, '
                f'account_type={self.account_type!r}, '
                f'taxability_type={self.taxability_type!r}, '
                f'member_i_ds={self.member_i_ds!r}, '
                f'current_balance={self.current_balance!r}, '
                f'current_holdings={self.current_holdings!r}, '
                f'cashflow_details={self.cashflow_details!r}, '
                f'additional_properties={self.additional_properties!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'account_id={self.account_id!s}, '
                f'account_type={self.account_type!s}, '
                f'taxability_type={self.taxability_type!s}, '
                f'member_i_ds={self.member_i_ds!s}, '
                f'current_balance={self.current_balance!s}, '
                f'current_holdings={self.current_holdings!s}, '
                f'cashflow_details={self.cashflow_details!s}, '
                f'additional_properties={self.additional_properties!s})')
